### ISSUE TITLE
Secure Suggest URI must use correct port

### ISSUE THREAD

**Issue by rudibatt** [Flagbit/Magento-FACTFinder#100]
At [Helper/Search::getSuggestUrl](https://github.com/Flagbit/Magento-FACTFinder/blob/master/src/app/code/community/Flagbit/FactFinder/Helper/Search.php#L349) the protocol of the direct suggest URI is changed, if the shop is in "secure mode" / accessed via https.
However the library puts the port directly into the link (even if that wouldn't be necessary) at [UrlBuilder::getNonAuthenticationUrl](https://github.com/Flagbit/Magento-FACTFinder/blob/master/src/lib/FACTFinder/Http/UrlBuilder.php#L206). This leads to the problem, that the browser tries to contact FACT-Finder via https over port 80.

To fix it, either the helper removes/corrects the port from the URL (which could be configurable as well?)
..or the UrlBuilder won't add the port if it's the default one. (This will lead to problems as soon as a not-default port is used => so not recommended)

**Comment by rudibatt** [comment]
Quick fix: configure HTTPS and port 443 in the module. (Prior to that, ensure that the FACT-Finder server is accessible over a "common trusted" certificate)

**Comment by tuegeb** [comment]
In version 4.x the port is configurable.
