### ISSUE TITLE
Variant ID returned from FF but not captured by Magento module

### ISSUE THREAD

**Issue by hollymurdoch** [Flagbit/Magento-FACTFinder#104]
Issue - Variant ID that is returned in a FF search response, is not captured and made available in Magento module
End goal - to display variant images using the variant id data

Magento environment
- Grouped products made visible to catalog & search
- Variant products managed as simple products, not visible
- Data exported to FF includes all variant data, except variant images

FACT-Finder
- Configured so that the grouped product is returned as the record id
- Variant id is returned within the FF response to Magento. E.g:

```
{
    "records": [
        {
            id": "9240",
            position": 1,
            "record": {
                "id": "9220",   //This is the data missing from Magento module
                "parent_id": "9240",
                ....
       }
    ]
}
```

Magento interepts this response as:

```
Array
(
    [searchResult] => Array
        (
            [records] => Array
                (
                    [0] => Array
                        (
                            [id] => 9240
                            [position] => 1
                            [record] => Array
                                (
                                    [parent_id] => 9240
                                )
                            [searchSimilarity] => 100
                            [simiMalusAdd] => 0
                        )
                )
        )
)
```

Magento module is therefore mapping the following:
FF record id - Module record id (Parent ID)
FF record > parent id - Module parent id (Parent ID)
FF record > id - Missing from Module (Variant ID)

**Comment by xpoback** [comment]
First, some questions:
Where did you dump that data array from ( the second one)?
Which version of the module are you using?

Then, we can easily add this field to the product data, but further customisation (making Magento show variant images on search) is beyond the current module requirements.

How would you like to have it: `$product->getVariantId()` or `$product->getFfVariantId()` ?

**Comment by hollymurdoch** [comment]
@xpoback please see responses to your questions below:

1. On the search result page
2. Magento ver. 1.9.2.1 and Fact-finder ver. 4.0.1-rc.2
3. $product->getVariantId()

**Comment by hollymurdoch** [comment]
@xpoback - To clarify

1. /src/app/code/community/FACTFinder/Core/Model/Resource/Search/Collection.php - public function _loadEntities
