### ISSUE TITLE
Export deeplink with preselected options for configurable product variants

### ISSUE THREAD

**Issue by KaiStapel** [Flagbit/Magento-FACTFinder#107]
This is a feature request.

For configurable products it would be nice to get a deeplink that links to the master product with preselcted options of the current variant in case the search result contains a specific variant.

Example:
Configurable product: ipad
Variant 1: ipad 64 GB
Variant 2: ipad 128 GB
When searching for "ipad 128" variant 2 will be returned. When clicking on it the detail page of the master product should be opened with option "128 GB" preselected.

Example link: http://magento.fact-finder.de/1.8.1.0/zolof-the-rock-and-roll-destroyer-lol-cat-t-shirt.html#525=99&272=22

525 and 272 are attribute IDs. 99 and 22 are option IDs.

This feature request might be related to https://github.com/Flagbit/Magento-FACTFinder/issues/104 or even solve it.

**Comment by xpoback** [comment]
@KaiStapel How soon would you like to have this feature and what is its priority?

**Comment by KaiStapel** [comment]
Currently, there is no urgent need for it. It was just an idea I did not want to forget about. Therefore I created this ticket. So, from my current perspective, it has a low priority.
