### ISSUE TITLE
Empty search request on every page triggered

### ISSUE THREAD

**Issue by tuegeb** [Flagbit/Magento-FACTFinder#108]
If the option "Redirect to product details page for single results" is enabled, the FACT-Finder PHP library call `$searchHandler->getArticleNumberStatus()` in the method `FACTFinder_Core_Model_Observer.handleSingleProductRedirect` triggers a search request even without having a search phrase. You can verify this through the factfinder.log after loading different pages in the shop (start page, product detail pages, shopping cart page etc.).

**Comment by tuegeb** [comment]
Please check the commit https://github.com/Flagbit/Magento-FACTFinder/commit/683c53fd62c7f8c73594d339112f85539aae1687 which has introduced this bug. The block type should be checked before the library call is made.

**Comment by xpoback** [comment]
In the above commit the abovementioned issue was resolved.

**Comment by tuegeb** [comment]
Many thanks.

**Comment by rudibatt** [comment]
I still observe this issue with the current version. As far as I found out, this happens because (advisor) campaigns are triggered on catalog pages, even when catalog navigation replacement is not active. Is this how it should be? At least the generated request should have a query or a navigation parameter.

**Comment by tuegeb** [comment]
The check for campaigns should only be made, if the catalogue navigation is replaced by the FACT-Finder shop navigation. This check should only be made in the `Observer` class of the core and sub modules using the already requested result and should not trigger an empty search request, if additionally the campaign manager is enabled. Advisory campaigns should be supported in search and navigation pages using the advisorStatus parameter together with the query respectively navigation parameter. Consequently no empty searches are wanted.

**Comment by hollymurdoch** [comment]
Possibly related. Also experiencing that Tracking.ff requests are made without any product detail params or event params. As a result, FF application logs this as an error

**Comment by Jayo-IRE** [comment]
This issue is being reported on multiple installations. Has there been any progress on a fix?

**Comment by xpoback** [comment]
@hollymurdoch Could you please give us more details about the tracking error you're experiencing?

**Comment by tuegeb** [comment]
I have tested it using the branch https://github.com/tuegeb/Magento-FACTFinder and could not observe empty tracking requests. But there is still an empty search request made when opening the Advanced Search page. Furthermore invalid requests are made using parameters like price=&price=&query= for every single advanced search request. 
Could you ensure that no advanced search functionality is overridden with this module, please? Thank you in advance.

**Comment by xpoback** [comment]
@tuegeb The single product redirect was being checked all the time on advanced search page. Not anymore.

**Comment by tuegeb** [comment]
Great, many thanks.
