### ISSUE TITLE
Option to enable module in single store needed

### ISSUE THREAD

**Issue by tuegeb** [Flagbit/Magento-FACTFinder#109]
Please provide the "Enabled" option which includes the connection check also on the store specific configuration page.

**Comment by tuegeb** [comment]
All configuration options (check restrictions in core - https://github.com/Flagbit/Magento-FACTFinder/blob/master/src/app/code/community/FACTFinder/Core/etc/system.xml - and sub module configurations) should be made accessible in the store scope in order to be more flexible.

**Comment by rudibatt** [comment]
Isn't it just necessary to set these flags to "1": https://github.com/Flagbit/Magento-FACTFinder/blob/master/src/app/code/community/FACTFinder/Core/etc/system.xml#L42
?

**Comment by xpoback** [comment]
@rudibatt It looks like it should be enough. But it wasn't tested like this, so this is what I'm doing at the moment .

**Comment by xpoback** [comment]
Everything looks working now.

**Comment by rudibatt** [comment]
Cool, thanks.

**Comment by tuegeb** [comment]
In https://github.com/Flagbit/Magento-FACTFinder/blob/master/src/app/code/community/FACTFinder/Core/Model/Observer.php#L76 something is missing: You should set the updated "enabled" state in the store or website specific scope and only as a default in the default scope. Otherwise a connection problem in the store scope would disable the module globally when saving the configuration.

**Comment by rudibatt** [comment]
I think this also needs to be considered at FACTFinder_Core_Model_Observer::setSearchEngine

**Comment by rudibatt** [comment]
One more problem with just one sub store active: FACTFinder_Tracking_Model_Observer::processOrderQueue is not processed when running the cron job, since `Mage::app()->getStore()->getConfig('factfinder/search/enabled')` returns false.

I guess this is not as an easy task as assumed in the first step. :(

**Comment by rudibatt** [comment]
Ok, I used this patch for a customer to fix this:
```
--- a/src/app/code/community/FACTFinder/Tracking/Model/Observer.php
+++ b/src/app/code/community/FACTFinder/Tracking/Model/Observer.php
@@ -209,6 +209,16 @@ class FACTFinder_Tracking_Model_Observer
     public function processOrderQueue()
     {
         if (!Mage::helper('factfinder')->isEnabled('tracking')) {
+            $stores = Mage::app()->getStores();
+            foreach($stores as $store) {
+                if ($store->getConfig('factfinder/search/enabled') && $store->getConfig('factfinder/modules/tracking')) {
+                    Mage::app()->setCurrentStore($store);
+                }
+                break;
+            }
+        }
+
+        if (!Mage::helper('factfinder')->isEnabled('tracking')) {
             return;
         }
```

Not sure if this solution/patch is OK this way?
In any case it reveals the problem, that different stores may have different FF connections configured but only one will be used (earlier it was simply the main config, with this patch it's just the first one). I guess no one ever noticed this, because no one used different FACT-Finder instances for different Magento stores. => #125

**Comment by xpoback** [comment]
The above commit should fix the problem. Now also the correct store view configuration should be used for status check, when saving the configuration.

Tracking and cronjob - it's another issue, not directly related to this one.

**Comment by tuegeb** [comment]
Thanks for the improvements. When saving the configuration, in the Magento `system.log` the following message is logged: 
`Recoverable Error: Argument 2 passed to Mage::getSingleton() must be of the type array, string given, called in \magento\app\code\community\FACTFinder\Core\Helper\Backend.php on line 206`
Could you check that, please?

**Comment by tuegeb** [comment]
Many thanks.
