### ISSUE TITLE
Fatal Errors - Site down 

### ISSUE THREAD

**Issue by Bobspadger** [Flagbit/Magento-FACTFinder#112]
We are (every 2-3 days) having our site knocked offline.
The only fatal errors in the PHP log at the time (and just before) are below

``` 
PHP Fatal error:  Call to undefined method Flagbit_FactFinder_Helper_Search::getEntity() in
/app/code/community/Flagbit/FactFinder/Helper/Search.php on line 328
```

The code related to this is:

```
    /**
     * get Entity ID Field Name by Configuration or via Entity
     *
     * @return string
     */
    public function getIdFieldName()
    {
        $idFieldName = Mage::getStoreConfig(self::XML_CONFIG_PATH_PRODUCT_IDENTIFIER);
        if(!$idFieldName){
            $idFieldName = $this->getEntity()->getIdFieldName();
        }
        return $idFieldName;
    }
```

We seem to end up with magento failing into itself and routing everything via /core/index/index and is unable to find the correct path for JS and CSS

**Comment by xpoback** [comment]
The error you mentioned was recently fixed in the latest release
https://github.com/Flagbit/Magento-FACTFinder/releases/tag/3.6.3
