### ISSUE TITLE
Do not send categories to fact finder

### ISSUE THREAD

**Issue by Bobspadger** [Flagbit/Magento-FACTFinder#115]
While this is a useful feature, it has one issue in that whilst not sending the products to fact finder, you can no longer view the products in the category in the front end 

Is there an over ride for this?

**Comment by xpoback** [comment]
@Bobspadger could you please specify the feature you mentioned?

**Comment by Bobspadger** [comment]
This is with relation to the 3.6.3 version.

System > Config > Fact-Finder > Fact-Finder > Export Config Settings

We use the navigation module of fact-finder, so if we omit some categories, then by return, we cannot show the products in the categories in magento, as FF does not know about them.

Ideally, we can exclude sending the categories to Fact-Finder, but still display the categories + products in our store (just outside of FF)

**Comment by xpoback** [comment]
@Bobspadger Does the fixe in #146 and #144 solve this?
The newest version 4.1.10 has  a setting, which allows you to include products without categories to the export, and there fore FF knows about then and they can be displayed.
