### ISSUE TITLE
Sorting items based on FF response

### ISSUE THREAD

**Issue by tuegeb** [Flagbit/Magento-FACTFinder#119]
The drop-downlist for sorting should be based on the sorting items which are part of the search/navigation response. This will partially solve the issue #127.

**Comment by xpoback** [comment]
@tuegeb It's relatively easy to implement, but we would also need (translated) labels from FF. Currently we get something like `sort.priceDesc` from the library, which is rather a code, but not a label to display.

**Comment by tuegeb** [comment]
Since FF7.1.1 their  labels can easily be set via the FF management interface. Using the sorting items based on the response should therefore be optional.

**Comment by xpoback** [comment]
Can you please advise where exactly it's in the management interface?

**Comment by tuegeb** [comment]
They are available in the current FF-UI under Basic settings > Result listing

**Comment by xpoback** [comment]
Too bad I only have access to 6.11 interface, which I actually use for testing and development.

**Comment by tuegeb** [comment]
That's no problem: If the new option "Use sorting options" (default: disabled) is active, all the sorting elements with their labels - in the dev system: for example `sort.priceDesc` - will replace the configured sorting attributes and be used in the front-end.

**Comment by tuegeb** [comment]
Thanks for the fast implementation. It works fine. There is only one minor issue: The arrow with the title "Set Ascending Direction" respectively "Set Descending Direction" besides the drop-down list with the sorting items isn't functional anymore.

**Comment by xpoback** [comment]
How should it behave in case if there is no direction in the filter? Since we have separately "desc" and "asc" items in the dropdown, the arrow button is redundant, I think. Or any suggestions?

**Comment by tuegeb** [comment]
Independently from the entries in the drop down list, every field - except the relevance sorting item - supports both sorting directions. Consequently the arrow has to change the sorting direction. Alternatively it could be removed.

**Comment by xpoback** [comment]
At the moment those sort items, that are not available in FF, are not working. I would suggest to keep this, since currently the collection gets sorted according to FF results and combining this and the default Magento functionality would need some effort, which is incomparable to the (un-) importance  of this small feature.
The button of changing sorting directions I'm going to fix, though.

**Comment by tuegeb** [comment]
Okay, that's fine.

**Comment by tuegeb** [comment]
@xpoback: Will this improvment be finalized soon?

**Comment by xpoback** [comment]
@tuegeb Yes in one or two days. Thanks for reminding.

**Comment by xpoback** [comment]
@tuegeb Seems to be fixed now.

**Comment by tuegeb** [comment]
Thanks. I have made some more changes for "special" field names: 0e0ce6b

**Comment by tuegeb** [comment]
When using Magento hosted in a subdirectory, the base path is duplicated. It similar to #131.
Could you solve this, please?
Thank you in advance.

**Comment by tuegeb** [comment]
@xpoback: Now it is solved.
