### ISSUE TITLE
Improve attributes product export

### ISSUE THREAD

**Issue by tuegeb** [Flagbit/Magento-FACTFinder#121]
The explicitly configured attributes for the export - mainly multi-select and other attribute types - should optionally be part of the fields "filterable_attributes" and "numerical_attributes" instead using one field per attribute in the product export.
For each attribute it should be possible to configure its type (number or text) for the export. Numerical attributes should additionally provide a configurable unit.

Sample entries:
numerical_attributes: `|length~~cm=10.25|width~~mm=50.50|parts=5|`

Expected new export config option:
- Add explicitly selected attributes to "numerical_attributes/filterable_attributes"

Expected new options for each attribute which was added through the button "Add attribute":
- Data type <- select box with the values "text", "number"
- Unit <- input field that will be editable if data type "number" was chosen

**Comment by tuegeb** [comment]
@xpoback: Any news regarding this issue? I am looking forward to your answer.

**Comment by xpoback** [comment]
@tuegeb So far no news. Which priority does it have?

**Comment by tuegeb** [comment]
average prio

**Comment by tuegeb** [comment]
@xpoback: When can the implementation be expected?

**Comment by xpoback** [comment]
@tuegeb Since the budget has been exceeded long ago (mainly on support issues), definitely not in this month and then, maybe, if we won't get too much bug fixing work, there will be some hours left for implementations of new features, but I wouldn't be very optimistic.
At the current tempo I would expect this to be done by the end of January.

**Comment by xpoback** [comment]
@tuegeb This was implemented (develop). 
I'm not sure it is exactly what was expected.
There is a setting `Use explicit attribute settings`. If it's set to `No`, the behavior is as before - each configured attribute in a separate field.
If it's set to `Yes`, then text attributes go to filterable, and number to numerical ones.
Another question is if there still should be the possibility to add separate columns to the export file, if that setting is `yes`

**Comment by tuegeb** [comment]
@xpoback:
If `Use explicit attribute settings` is enabled, only additional attributes that are configured as filters via Magento attribute management for the (search results) layered navigation, should be exported in the two multi-attribute fields. Pure sorting or system attributes  should be included in the export as additional fields if they are not additionally flagged as a filter in Magento.

In the case of the numeric attributes, the compliance with the en-US format should also be ensured. Thousands grouping characters must not be exported. In addition, point must be used as a decimal separator. Perhaps you can consider the currency format configured in the respective store or in addition to the optional unit, a locale for the input format. Thus, an attribute which has the configured type "Number" and eventually an unit (e.g. AnyNumericAttribute=2.345,67), would be included in the "numerical_attributes" field formatted as follows: AnyNumericAttribute~~AnyUnit=2345.67

**Comment by xpoback** [comment]
I added some formatting logic. So far it worked well for me.

**Comment by tuegeb** [comment]
@xpoback: Thanks for the implementation. The following issues have been identified:
- empty units should not be exported as _anyNumericAttribute~~=012345_ -> instead _anyNumericAttribute=012345_ is expected
- "special" characters like m² etc. should not be forbidden in the unit field -> instead all characters which are covered by the pattern _([\u0020-\u0022\u0024-\u003c\u003e-\u007b\u007d\u00a0-\u00bb]+)_ should be accepted and thus only the reserved characters ~|=# be exluded
- multi-attribute values are not exported in the expected format. If there are the values a, b and c currently _multiattribute=abc_ will be exported. Instead the following key value pairs are expected:  _multiattribute=a|multiattribute=b|multiattribute=c_
- numerical attributes of type _date_ are cut. Instead of _rtrim_ the method _round_ should be used. Additionally the decimal places should be limited to _4_.
- explicitly configured static attributes should _not_ be exportes twice, once in the numerical_attributes or filterable_attribute and additionally in separate columns

**Comment by xpoback** [comment]
@tuegeb Thank you for the detailed report. I'll take care of these problems asap.

**Comment by xpoback** [comment]
@tuegeb So far, all the problems, reported above, appear to be fixed to me.
I removed any validation for the unit field, I think this should be OK.

**Comment by tuegeb** [comment]
@xpoback: Thanks for the bugfixes. 
One new export issue should be resolved:
System attribute values should not be added to the field "searchable_attributes". I have noticed that values of the default system attribute "tax_class_id" are exported into the search data field.
Could you solve that, please? Thank you in advance.

**Comment by xpoback** [comment]
@tuegeb What kind of error message do you get in your system.log? Under which circumstances?

**Comment by tuegeb** [comment]
@xpoback: Thanks for the analysis. The system attributes which are marked as searchable should be kept in the "searchable_attributes". Thus no changes are needed here at the moment.

The message is logged with/without explicit type consideration:

```
2017-03-06T18:01:28+00:00 ERR (3): Notice: Undefined index: numerical  in /var/www/magento/public_html/dev_1.9.2.4/app/code/community/FACTFinder/Core/Model/Export/Type/Product/Attribute.php on line 300
2017-03-06T18:01:28+00:00 ERR (3): Warning: in_array() expects parameter 2 to be array, null given  in /var/www/magento/public_html/dev_1.9.2.4/app/code/community/FACTFinder/Core/Model/Export/Type/Product/Attribute.php on line 300
```

**Comment by tuegeb** [comment]
@xpoback: Thanks for the bugfix. After an update of the version in https://github.com/Flagbit/Magento-FACTFinder/blob/develop/package.xml#L12 and the addition of a default size for the suggest images (60 px. in https://github.com/Flagbit/Magento-FACTFinder/blob/develop/src/app/code/community/FACTFinder/Suggest/etc/system.xml#L43), the version 4.1.13 should be released.
Many thanks in advance.
