### ISSUE TITLE
ASN not shown sometimes

### ISSUE THREAD

**Issue by rudibatt** [Flagbit/Magento-FACTFinder#122]
For some reason the ASN was not shown some times and I found the following reason:

To decide whether the ASN should be shown or not, the default templates calls "Mage_CatalogSearch_Block_Layer::canShowBlock()". At this method the configuration value "catalog/search/use_layered_navigation_count" is fetched and if it's greater 0, that value is compared against "a product collection" from the database (which seems to be a Magento bug, since it actually should ask the engine! Fortunately this causes only a "select count" query, which is much faster than a full search)

Since I don't know how to file a bug at Magento, there should be a workaround for this. :-/

A quick fix is to set that configuration ("System" > "Configuration" > "Catalog" > "Catalog Search" > "Apply Layered Navigation if Search Results are Less Than") to "0", so that comparison is completely disabled.

**Comment by xpoback** [comment]
Can you check this again please? After https://github.com/Flagbit/Magento-FACTFinder/commit/00813e0b3a85caf5339176bedf56c18ecccf8ce3 it should not happen anymore.

**Comment by tuegeb** [comment]
@xpoback: 
Should there not be a special handling in case the fallback search feature is active?

**Comment by xpoback** [comment]
@tuegeb this is already included into `isEnabled` function, when the fallback feature is active, it returns false.

**Comment by tuegeb** [comment]
Ok, thanks. From my point view this issue is solved. Probably @rudibatt won't check this anymore.

**Comment by tuegeb** [comment]
The current version doesn't solve this issue.
@xpoback: Please override the method `canShowBlock` in order to solve this issue.

**Comment by xpoback** [comment]
@tuegeb I couldn't reproduce the issue, but just in case we will always show layer navigation if the module is enabled and the number of results is between 0 and the max allowed number.

**Comment by tuegeb** [comment]
@xpoback: Using 0 was fully functional, but in many cases this default setting has not been adjusted, so the idea was to remove this check, because all ASN related settings are made on FACT-Finder side and therefore the Catalog search settings on Magento side should completely be ignored.

**Comment by xpoback** [comment]
@tuegeb Okay

**Comment by tuegeb** [comment]
Now it works fine, many thanks.
