### ISSUE TITLE
ensure dependent min php version is kept

### ISSUE THREAD

**Issue by rudibatt** [Flagbit/Magento-FACTFinder#124]
At [FACTFinder_Core_Model_Export_Product::_getExportAttributes](https://github.com/Flagbit/Magento-FACTFinder/blob/master/src/app/code/community/FACTFinder/Core/Model/Export/Product.php#L154) the short syntax for array creation is used (`$arr = [];`) which is [available since PHP 5.4](http://php.net/manual/en/language.types.array.php). 

However the [depends_php_min setting](https://github.com/Flagbit/Magento-FACTFinder/blob/master/package.xml#L26) is set to PHP 5.3, which might be the reason (or not?), why the module is installed without problems. 

Anyways - a defined compatibility level should be defined and the code should keep that definition.

**Comment by xpoback** [comment]
@rudibatt In the beginning it was planned the the module should support 5.3, but it was mainly tested on 5.4 and 5.5. We can either find all possible incompatibilies, or claim 5.4 as the min supported version.

**Comment by rudibatt** [comment]
I don't care... ;) imho it should just be defined somewhere and tests or something similar should ensure it.

**Comment by tuegeb** [comment]
Could you solve this problem asap and ensure that this module requires only PHP 5.3, please?
