### ISSUE TITLE
checkout tracking not correct for different FF connection configs

### ISSUE THREAD

**Issue by rudibatt** [Flagbit/Magento-FACTFinder#125]
As mentioned in #109, the cron job which sends the checkout events to FF has a problem: if different Magento stores have different FACT-Finder stores configured, only the first / main one is used. This means all checkout events are sent to the FF instance/channel which is configured for the first store.

**Comment by xpoback** [comment]
The last commit should resolve the issue: a separate adapter is now used for each store with different configurations.
