### ISSUE TITLE
invalid product campaign requests from product detail pages

### ISSUE THREAD

**Issue by rudibatt** [Flagbit/Magento-FACTFinder#126]
"ProductCampaign.ff" requests from product detail pages have not "productNumber" parameter. I didn't get the system how that should work, I just see the requests in the access logs of the FF server.
The product campaigns from the shopping cart page work fine. Please check that.

**Comment by rudibatt** [comment]
Ok, the bug is a bit stranger than expected: even if campaigns are disabled for product detail pages, they are triggered from there.

**Comment by xpoback** [comment]
@rudibatt Can you please describe steps to reproduce this issue?

I tried product page and get no requests if campaigns are disabled, either generally or for product pages. Also when the campaigns are enabled, there's always productNumber: either ID or SKU

**Comment by rudibatt** [comment]
These requests appeared in a system with many other modules installed, a custom template but with a standard FF module, whenever a product detail page was loaded. But I wasn't able to find the cause of these requests. It's very likely this is an issue related to the customer's system.

However I have no access to that system anymore, so I guess this is a "can't reproduce" issue...

**Comment by xpoback** [comment]
Ok then, _can't reproduce_

**Comment by tuegeb** [comment]
Please investigate this because I have observed it recently in two customer setups. There might be a bug in the campaign sub-module which does not depend on custom templates.

**Comment by xpoback** [comment]
@tuegeb Any other details about how I could reproduce this or at least how it appeared at your side and what exact messages you got, please?

**Comment by tuegeb** [comment]
Sorry for the late reply. After some more tests (using the branch https://github.com/tuegeb/Magento-FACTFinder) I could not reproduce this bug locally. Maybe the customer has used additionally older versions of this module at the same time in different systems.
In order to avoid this and simplify the update to the head revision, could you please provide the latest version of this module (would be version 4.0.6+) via Magento Connect? Thank you in advance.

**Comment by xpoback** [comment]
@tuegeb The newest release 4.0.6 was added and uploaded to Magento Connect.
In any case is the module not approved yet, so it's not accessible for normal user from the magento website.

**Comment by xpoback** [comment]
So far we weren't able to reproduce the problem

**Comment by tuegeb** [comment]
Now I could reproduce it:
Currently it happens only on the shopping cart page after you have removed the last item. The resulting request url has no mandatory parameter "productNumber":
`ProductCampaign.ff?do=getShoppingCartCampaigns&channel=de&idsOnly=true&format=json...`

**Comment by tkn98** [comment]
@xpoback: I can also confirm that the issue is still immanent with 4.0.9. 

> productNumber parameter should be provided even if empty (Omicron)

**Comment by tuegeb** [comment]
Solved: 6176aa2.
@tkn98: Could check the version in the master branch, please?

**Comment by tkn98** [comment]
I took 4.1.5, testing in a staging system
