### ISSUE TITLE
Bug: parent category or attribute name with space character not supported 

### ISSUE THREAD

**Issue by tuegeb** [Flagbit/Magento-FACTFinder#127]
If a category contains a space character (e.g. House & Garden) and its sub category (e.g. House & Garden -> Chairs) is selected, choosing a sorting option which is not configured for the FF response the request will fail. The reason for that is a missing mapping in https://github.com/Flagbit/Magento-FACTFinder/blob/master/src/app/code/community/FACTFinder/Core/Block/Catalog/Product/List/Toolbar.php for the search parameters which are needed for every single sorting item. Without this, the space character in the parameter name will be replaced by an underscore.

Parameters before sorting:
filtercategoryROOT=House%20%26%20Garden
filtercategoryROOT%2FHouse%20%26%20Garden=Chairs
Parameters after sorting:
filtercategoryROOT=House%20%26%20Garden
filtercategoryROOT%2FHouse_%26_Garden=Chairs

In case of an attribute filter the chosen attribute will "only" be ignored by FF, because if differs from the expected parameter name after the sorting:
before: filterlength%20inch=10
after: filterlenght_inch=10

Also for a slider group, a space character in the filter name is not supported. The module duplicates the filter parameter. Finally there is one filter with the space character encoded twice and one with space replaced by underscore, but no filter parameter with the space character encoded once.

**Comment by xpoback** [comment]
@tuegeb I tried to reproduce the issue with category name, but the only place where it appears in the "View as (List|Grid)" links (which should be fixed as well for sure). Can you describe the exact steps, please?
Regarding filters, attribute codes cannot contain spaces and with values it works so far good.

**Comment by tuegeb** [comment]
@xpoback:
The sorting item issue can be reproduced as follows:
- ensure parent category with special character (space, %, +, /, etc.) is given in the data feed for FACT-Finder
- make attribute which is included in the data feed available for sorting on Magento side
- miss to make the corresponding attribute sortable on FACT-Finder side
- search or browse in the shop and finally filter on a sub category of the parent category with special character
- choose this sorting option in the result listing
= 0-hit page will show up

**Comment by xpoback** [comment]
Ok, got it. If the filter is not available for sorting from FF, the issue is easily reproduceable.I missed this point at the first place.

**Comment by xpoback** [comment]
The last commit should fixes the issue. The problem is actually in PHP, where all "strange" parameter names get underscored in the $_GET variable before Magento uses them to build links. I had to make a workaround for that.

**Comment by tuegeb** [comment]
Great, many thanks. The "view as" links are now also fully functional.

**Comment by potschntom** [comment]
Hi, I´m using commit 2bd4564 from 07.06.2106 and still having the problem that if I switch from Grid to list View that search result is empty because of space in filtercategory. The space should be replaced with "+" but is replaced with "_"

filtercategoryROOT/Bier/Bier+EW= 
becomes
filtercategoryROOT/Bier/Bier_EW=

and search result is empty

**Comment by xpoback** [comment]
@potschntom Yep, your issue is still in the queue.
Do you still have the same problem when using version 4.1.9?

**Comment by potschntom** [comment]
@xpoback I can´t update at the moment because of some customization. 
For me it looks like the code in Url.php is not executed.

Maybe that´s the problem?

**Comment by xpoback** [comment]
@potschntom That sounds like a reasonable explanation.

**Comment by tuegeb** [comment]
I can only confirm that the slider related bug is not solved. The other URLs are already corrected.

**Comment by xpoback** [comment]
@tuegeb Provide me please with the steps to reproduce the issue. Thanks.

**Comment by tuegeb** [comment]
Create a field copy and an additional price filter (one with type slider and the other with type ranges) via the FACT-Finder Basic settings 
> Field summary 
 > Add a field
 > Field name = "Min. Price" 
 > Data source = "Combination field" 
 > Add combination source = "price" <= the field from the product feed
 > Data type = "Number"

> Filters
 > Add Filter with type "slider" based on the new field

> Use the slider filter in the front-end

**Comment by xpoback** [comment]
@tuegeb This has been fixed and now the slider works. 
Even though it's a bit strange to have attribute(filter) codes with spaces, nevertheless now it's supported.

**Comment by tuegeb** [comment]
@xpoback: Thanks for the bugfix.
