### ISSUE TITLE
Configuration of secondary channel fails and no parallel search requests made

### ISSUE THREAD

**Issue by tuegeb** [Flagbit/Magento-FACTFinder#133]
When trying to save the configuration - using the head revision of this module - the following stack trace is printed:
`
( ! ) Fatal error: Call to a member function getStatusCode() on a non-object in ...\www\magento\app\code\community\FACTFinder\Core\Model\Facade.php on line 671
`
Anyway the suggest module requests both channel results, but in the quick search only one request is made.

**Comment by xpoback** [comment]
@tuegeb The error has just been fixed. 
Secondary requests work well with the suggest proxy enabled. Without the proxy only one request is made, since it was not implemented in the JS side.

**Comment by tuegeb** [comment]
Many thanks. 
When saving the configuration, currently the primary channel is used multiple times for the connection check. Is the search adapter reused? Could you check this please? Thanks.

**Comment by xpoback** [comment]
@tuegeb Now it checks the channels correctly
