### ISSUE TITLE
Advanced search should not use FACT-Finder

### ISSUE THREAD

**Issue by tuegeb** [Flagbit/Magento-FACTFinder#134]
After every advanced search and when opening the advanced search page using the quick link in the default template, an empty search request will be triggered. In the test shop - uses module version 4.0.6 -  only the search and tracking module were enabled.

**Comment by xpoback** [comment]
Campaign submodule was making requests to check if there are redirects on single product result. This is the only thing I found on advanced search so far

**Comment by tuegeb** [comment]
Please check all observers. So far a controller name check is missing in the Observer.php of the Tracking sub-module:

`    public function addTrackingHandles($observer)
    { 
		if (Mage::app()->getRequest()->getControllerName() !== 'result') {
                return;}
                ...
`

Maybe this check could be added to the method `getIsOnSearchPage`.

**Comment by xpoback** [comment]
Now it should be looking better

**Comment by tuegeb** [comment]
Yes, it can confirm that it's solved with the last patch.
