### ISSUE TITLE
FTP upload and ZIP support

### ISSUE THREAD

**Issue by tuegeb** [Flagbit/Magento-FACTFinder#136]
The shell script and Magento cronjob should support ZIP files and the upload of the successfully created product, price and stock data feeds via FTP.

If FTP option is enabled, there should be the following process
- creation of a new zip file which bundles the three files of a store
- upload of the zip file
- import trigger

**Comment by xpoback** [comment]
Any information about where to upload the files? Or should all this be configurable?

**Comment by tuegeb** [comment]
The required configuration options are as follows:
- FTP URL
- Protocol (ftp and ftps)
- Username
- Password
- Path (default: empty = home directory of the ftp user)

**Comment by xpoback** [comment]
@tuegeb The feature is ready to be tested in the [branch](https://github.com/Flagbit/Magento-FACTFinder/tree/FACTFINDER-159)
Some piece of documentation has been added [here](https://github.com/Flagbit/Magento-FACTFinder/wiki/Data-Export#ftp-upload)

**Comment by tuegeb** [comment]
@xpoback: Thanks.
The creation of a ZIP file failed with the following message:

`2016-06-20T09:26:02+00:00 ERR (3): Warning: ZipArchive::addFile(): Invalid or uninitialized Zip object  in magento\app\code\community\FACTFinder\Core\Helper\Export.php on line 196`

**Comment by tuegeb** [comment]
With the latest revision, the uploaded files have the file size of 0 bytes.

**Comment by xpoback** [comment]
@tuegeb I could not reproduce the problem, the files get created, packed  and then successfully uploaded to my test FTP. Can you please provide me the conditions under which you get  the issue?

**Comment by tuegeb** [comment]
@xpoback:
I have used the Magento System Cronjob for the export in all stores with a FTP connection - not ftps - and a custom remote directory.
With the Magento demo data the process lasted several minutes, although the product export creation usually takes only a few seconds.

**Comment by xpoback** [comment]
@tuegeb And no exceptions, no warnings? Archivation and uploading is triggered at the end of each product export, so it might be something wrong with the export. Try to run export without it. Unfortunately I can't reproduce the problem.

**Comment by tuegeb** [comment]
The csv file is up-to-date and the locally created ZIP file is also valid and not empty.
According to the exception.log an exception has been thrown:

```
2016-06-21T14:24:18+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Unable to upload file to FTP' in magento\app\Mage.php:595
Stack trace:
#0 magento\app\code\community\FACTFinder\Core\Model\Ftp.php(105): Mage::throwException('Unable to uploa...')
#1 magento\app\code\community\FACTFinder\Core\Model\Observer.php(300): FACTFinder_Core_Model_Ftp->upload('C:\\xampp\\htdocs...')
#2 magento\app\code\community\FACTFinder\Core\Model\Observer.php(257): FACTFinder_Core_Model_Observer->uploadFileToFtp(Object(Varien_Event_Observer))
#3 magento\app\code\core\Mage\Core\Model\App.php(1358): FACTFinder_Core_Model_Observer->triggerImportAfterExport(Object(Varien_Event_Observer))
#4 magento\app\code\core\Mage\Core\Model\App.php(1337): 
```

**Comment by tuegeb** [comment]
It was locally just a firewall issue. There was still an issue regarding the default directory. The corresponding error message was:
```
2016-06-21T19:44:42+00:00 ERR (3): 
exception 'Mage_Core_Exception' with message 'Unable to change FTP directory' in C:\xampp\htdocs\magento\app\Mage.php:595
Stack trace:
#0 C:\xampp\htdocs\magento\app\code\community\FACTFinder\Core\Model\Ftp.php(134): Mage::throwException('Unable to chang...')
```
I have solved it.
