### ISSUE TITLE
Wrong JSONP Request-Handling

### ISSUE THREAD

**Issue by mralexandernickel** [Flagbit/Magento-FACTFinder#145]
If i want to write an own suggestbox, i need to do a JSONP Request. But if I'm requesting without the jquery_callback-parameter (but WITH the callback-parameter) i'll get a malformed response (the callback-name is missing).

**Comment by xpoback** [comment]
@mralexandernickel Please, test.

**Comment by mralexandernickel** [comment]
@xpoback I have tested and can confirm that it's working now as expected...good job! 🚀
