### ISSUE TITLE
Allow products with no category #144

### ISSUE THREAD

**Issue by bjoern-flagbit** [Flagbit/Magento-FACTFinder#146]
We will do an configuration for that and in default it is set to "no" so for nobody will change anything. And for our customer we change the configruation to "yes" to export also products without categories.

Is that okay @rudibatt ?

I just create a issue for this pullrequest:
https://github.com/Flagbit/Magento-FACTFinder/pull/144/commits/61838dc8d96058ad45ee9f0da691ef4e1e9058a4

**Comment by tuegeb** [comment]
Solved in 59c653d.
