### ISSUE TITLE
CSV: No linebreaks in articledata requirement violated by extension

### ISSUE THREAD

**Issue by tkn98** [Flagbit/Magento-FACTFinder#151]
Report against: v4.0.9 / cd8e89559dab724955bf41ead32ae39ab3934a47

Requirement for FF 7.0 via:

> Artikeldaten dürfen keine Zeilenumbrüch enthalten (Aufbau des Datenexport in der Suchumgebung)

(it's from a German PDF File "`FACT-Finder_7.0_Aufbau_des_Datenexports_für_die_Suchumgebung_de_v1.0.pdf`")

Can you please fix the export so that CSV files do match with the import requirements of Fact-Finder reagarding line-breaks (linenedings)?

In my concrete case we have problems with the field "`description`" but I can imagine other fields could be affected by this as well.

**Comment by tuegeb** [comment]
see 73188b1

**Comment by tkn98** [comment]
I've seen in the adminhtml backend that there is now an option to strip tags. Probably the data filtering / normalization has moved into another place?

**Comment by tuegeb** [comment]
With above commit it's solved. The mentioned option takes only care of html entities and tags.

**Comment by tkn98** [comment]
@tuegeb: Thanks for the tagged update, we'll give this a try.

**Comment by tkn98** [comment]
Fix in 4.1.4
