### ISSUE TITLE
Installation with PHP > 5.5 via Magento Connect not supported

### ISSUE THREAD

**Issue by tuegeb** [Flagbit/Magento-FACTFinder#153]
The following error message interrupts the installation process:

> 
CONNECT ERROR: Package community/Flagbit_Factfinder 4.1.1: requires PHP version >= 5.3.0 and <= 5.5.0 current is: 5.6.20

The max supported PHP version should be increased.

**Comment by xpoback** [comment]
Should it be changed for all the versions?
Versions since 4.1.4 are already 5.6 tolerant.

**Comment by tuegeb** [comment]
@xpoback: Magento Connect provides only the version 4.1.1. Could you upload the 4.1.6 to Connect, please?
Thank you in advance.

**Comment by tuegeb** [comment]
@xpoback: Are there any news regarding this issue?

**Comment by tuegeb** [comment]
@DennisU: Could you upload https://github.com/Flagbit/Magento-FACTFinder/releases/tag/v4.1.8 to Magento Connect, please?

**Comment by xpoback** [comment]
@tuegeb Uploaded version 4.1.9 with the last fixes to Magento Connect. It is now 5.3 - 7.1 compliant.

**Comment by tuegeb** [comment]
@xpoback: The installation via Connect failed. 

There is no menu item System > Configuration > FACT-Finder, after the installation and cache flush:

![connect-setup](https://cloud.githubusercontent.com/assets/7773050/18001583/e1b9ca04-6b83-11e6-9b09-fc0baa17e172.PNG)

Could you solve this issue asap, please? Thank you in advance.

**Comment by xpoback** [comment]
Module registration files in app/etc/modules/ were missing. I included them to the package.
Since there's no way to delete a version in Magento Connect, I added it with a mark Fixed.

**Comment by tuegeb** [comment]
@xpoback: Many thanks for the bugfix.
