### ISSUE TITLE
SKU Direct Hit for Wrong Website Catalog

### ISSUE THREAD

**Issue by tkn98** [Flagbit/Magento-FACTFinder#155]
We have direct single result hit redirection to a product page (despite feature is ***deactivated***) but anyway an (imaginary) direct hit triggers a 302 redirect to a product page (in the wrong website) therefore triggering a 404.

Debug log shows that searches to FF backend are legit.

Problem is the 302 to the 404.

First flaw is that a product is identified as single hit while it's not part at all of that website.

Second grade flaw is that the option looks ignored when switched to "No".

**Comment by tkn98** [comment]
Details:

    $ n98-magerun.phar config:get 'factfinder/config/redirectOnSingleResult'
    +------------------------------------------+---------+----------+-------+
    | Path                                     | Scope   | Scope-ID | Value |
    +------------------------------------------+---------+----------+-------+
    | factfinder/config/redirectOnSingleResult | default | 0        | 0     |
    +------------------------------------------+---------+----------+-------+



![selection_049](https://cloud.githubusercontent.com/assets/10513307/15240468/2096a3d8-18ea-11e6-89c6-d46b54df3b02.png)

**Comment by tkn98** [comment]
@xpoback: Great to see some traction. Could you be so kind and ping me when you're able to reproduce?

**Comment by xpoback** [comment]
@tkn98 Unfortunately, I was not able to reproduce this.
Did you check all your campaigns, maybe the redirect originates from there? Are all the channels correct?
What result do you get when you search for the same thing in the FF management interface?

**Comment by tkn98** [comment]
@xpoback: Thank you for taking the time to look into this, much appreciated. Based on your feedback I've checked the settings and can provide you with the following information:

- There are no campaigns configured for the channel(s) in question. There are no active campaigns at all for the whole installment.
- Yes, all channel names are correct.
- In the FF management console I get the same result as I can see in the debug log: A search resultset with three entries.

This is also the state of information I had at the time of the report. As you can see from the third point, because I got a different result on the website than I got from the search webservice, my conclusion was that this might be subject of the extension that processes the webservice result.

Can you tell me a good location in the code where I can more or less quickly inspect if my conclusion is good?

**Comment by xpoback** [comment]
The only place where the single product redirect is performed in [this observer function](https://github.com/Flagbit/Magento-FACTFinder/blob/master/src/app/code/community/FACTFinder/Core/Model/Observer.php#L188).
Another point is [this function](https://github.com/Flagbit/Magento-FACTFinder/blob/master/src/app/code/community/FACTFinder/Campaigns/Model/Observer.php#L33) in the Campaign module.
These two are the only places that do redirects.

**Comment by xpoback** [comment]
@tkn98 How is the current situation?

**Comment by tkn98** [comment]
@xpoback: The regression #157 is blocking an upgrade to 4.1.5.

**Comment by tuegeb** [comment]
@tkn98  Could you check this again with the version 4.1.9, please?

**Comment by tkn98** [comment]
Sorry, I'm currently blocked on the issue.
