### ISSUE TITLE
Regression: PDOException after Upgrading to 4.1.5 (from 4.1.4)

### ISSUE THREAD

**Issue by tkn98** [Flagbit/Magento-FACTFinder#157]
Since version 4.1.5 we see the following **PDOException** which results from a `$query` object that is from the extension.

I could reproduce this on multiple systems, it happens after entering a text into the search box and pressing enter:

> `SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS `query_id`, `s`.`product_id`, 0 AS `relevance` FROM `catalogsearch_fulltext` ' at line 1, query was: INSERT INTO `catalogsearch_result` SELECT  AS `query_id`, `s`.`product_id`, 0 AS `relevance` FROM `catalogsearch_fulltext` AS `s`
 INNER JOIN `catalog_product_entity` AS `e` ON e.entity_id = s.product_id WHERE (s.store_id = 1) AND ((`s`.`data_index` LIKE '%test%')) ON DUPLICATE KEY UPDATE `relevance` = VALUES(`relevance`)`

This regression prevents us from updating to 4.1.5+, ref #156.

**Comment by tuegeb** [comment]
@xpoback: Could you check, if this is related to 6176aa2, please?

**Comment by xpoback** [comment]
@tuegeb, it is definitely related. But, @tkn98, I can't reproduce it. It surely can happen - it had been happening while I was looking for solution, but since I found it, I got no more errors like this with different combinations of settings and queries.
Does it happen only on new queries or on any?

**Comment by xpoback** [comment]
@tkn98 I can only reproduce this error on new queries (which are not yet in the `catalogseatch_query` table) and if the block `Mage_CatalogSearch_Block_Layer` is not rewritten by FACTFinder. 
Another option can be, that the function `isEnabled()` worked differently in `FACTFinder_Core_Model_CatalogSearch_Query` and `FACTFinder_Core_Block_CatalogSearch_Layer`,  but this is unlikely.

Unfortunately, rewriting these classes was the only option I found to prevent writing search queries to the db. It has not yet been mentioned in the documentation, but it, I think, worth it.

**Comment by tkn98** [comment]
@xpoback: I need a solution so that the fatal error is not triggered. As written in 4.1.4 I don't have this problem.

**Comment by xpoback** [comment]
@tkn98 In the previous comment I described the conditions, at which I am able to reproduce the problem. It would be very kind from your side to check if these conditions are the same on your side.
I fully understand your concerns, but without cooperation we won't be able to  find a common solution.
So please, check if the block `Mage_CatalogSearch_Block_Layer` is rewritten with `FACTFinder_Core_Block_CatalogSearch_Layer` in your installation. The easiest way to do it to put logs into the latter class and see if any of the methods inside are triggered.

**Comment by tuegeb** [comment]
@tkn98: Could you provide the complete stack trace (e.g. can be enabled in magento\lib\Varien\Db\Adapter\Pdo\Mysql.php > _logCallStack=true), please?

**Comment by tuegeb** [comment]
@xpoback: Are there any news regarding this issue?

**Comment by xpoback** [comment]
@tuegeb No news, as I mentioned before, the issue is only reproduceable when the block is no rewritten.
We also have the last extension version on a couple of projects and there's no problem like described.

**Comment by tkn98** [comment]
@xpoback: How can I verify on my end that the block is (not) rewritten? And should the block be rewritten? If yes, this could be some configuration issue as a rewrite conflict.

**Comment by xpoback** [comment]
@tkn98 the easiest way is to put some `die('testwhatever')` on your test instance in the above mentioned block in the beginning of the function `getLayer`. If the `die` is executed, then the block is overwritten.
Yes, a rewrite conflict is very probable, I would say 99% chance that there is one. In that case you must resolve it in the normal way. 
Unfortunately, we couldn't avoid rewrites in the module completely.

**Comment by tuegeb** [comment]
@hackwell: Can we expect the solution from  906bc2e in the version 4.1.8 next week?

**Comment by xpoback** [comment]
@tuegeb Yes, for sure. That would be nice if you merge it, I will be able to do it and test only on wednesday.

**Comment by tuegeb** [comment]
@tkn98: Should be solved with version 4.1.8. Could check and confirm, please? Thank you in advance.

**Comment by tuegeb** [comment]
@xpoback: Could you take a look on this, please?
According to a customer, there is still an issue when using version 4.1.8. In `app/code/core/Mage/CatalogSearch/Model/Resource/Fulltext.php(393) -> public function prepareResult($object, $queryText, $query)`: The `$query` is empty if is not loaded from the table `catalogsearch_query`. In the insert statement to `catalogsearch_result` the `$query` is needed. 

The complete stack trace:
```
a:5:{i:0;s:623:"SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS `query_id`, `s`.`product_id`, 0 AS `relevance` FROM `catalogsearch_fulltext` ' at line 1, query was: INSERT INTO `catalogsearch_result` SELECT  AS `query_id`, `s`.`product_id`, 0 AS `relevance` FROM `catalogsearch_fulltext` AS `s`
 INNER JOIN `catalog_product_entity` AS `e` ON e.entity_id = s.product_id WHERE (s.store_id = 2) AND ((`s`.`data_index` LIKE '%blaaaambb%')) ON DUPLICATE KEY UPDATE `relevance` = VALUES(`relevance`)";i:1;s:5185:"#0 /ANY_MAGE_HOME_DIR/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /ANY_MAGE_HOME_DIR/app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /ANY_MAGE_HOME_DIR/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /ANY_MAGE_HOME_DIR/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `ca...', Array)
#4 /ANY_MAGE_HOME_DIR/lib/Varien/Db/Adapter/Pdo/Mysql.php(504): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `ca...', Array)
#5 /ANY_MAGE_HOME_DIR/app/code/core/Mage/CatalogSearch/Model/Resource/Fulltext.php(393): Varien_Db_Adapter_Pdo_Mysql->query('INSERT INTO `ca...', Array)
#6 /ANY_MAGE_HOME_DIR/app/code/core/Mage/CatalogSearch/Model/Fulltext.php(136): Mage_CatalogSearch_Model_Resource_Fulltext->prepareResult(Object(Mage_CatalogSearch_Model_Fulltext), 'blaaaambb', Object(FACTFinder_Core_Model_CatalogSearch_Query))
#7 /ANY_MAGE_HOME_DIR/app/code/core/Mage/CatalogSearch/Model/Resource/Fulltext/Collection.php(55): Mage_CatalogSearch_Model_Fulltext->prepareResult()
#8 /ANY_MAGE_HOME_DIR/app/code/core/Mage/CatalogSearch/Model/Layer.php(58): Mage_CatalogSearch_Model_Resource_Fulltext_Collection->addSearchFilter('blaaaambb')
#9 /ANY_MAGE_HOME_DIR/app/code/core/Mage/CatalogSearch/Model/Layer.php(42): Mage_CatalogSearch_Model_Layer->prepareProductCollection(Object(Mage_CatalogSearch_Model_Resource_Fulltext_Collection))
#10 /ANY_MAGE_HOME_DIR/app/code/core/Mage/Catalog/Model/Layer.php(290): Mage_CatalogSearch_Model_Layer->getProductCollection()
#11 /ANY_MAGE_HOME_DIR/app/code/core/Mage/Catalog/Model/Layer.php(220): Mage_Catalog_Model_Layer->_getSetIds()
#12 /ANY_MAGE_HOME_DIR/app/code/core/Mage/Catalog/Block/Layer/View.php(163): Mage_Catalog_Model_Layer->getFilterableAttributes()
#13 /ANY_MAGE_HOME_DIR/app/code/core/Mage/Catalog/Block/Layer/View.php(122): Mage_Catalog_Block_Layer_View->_getFilterableAttributes()
#14 /ANY_MAGE_HOME_DIR/app/code/core/Enterprise/Search/Block/Catalogsearch/Layer.php(93): Mage_Catalog_Block_Layer_View->_prepareLayout()
#15 /ANY_MAGE_HOME_DIR/app/code/core/Mage/Core/Block/Abstract.php(293): Enterprise_Search_Block_Catalogsearch_Layer->_prepareLayout()
#16 /ANY_MAGE_HOME_DIR/app/code/core/Mage/Core/Model/Layout.php(456): Mage_Core_Block_Abstract->setLayout(Object(Mage_Core_Model_Layout))
#17 /ANY_MAGE_HOME_DIR/app/code/core/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('enterprise_sear...', 'enterprisesearc...')
#18 /ANY_MAGE_HOME_DIR/app/code/core/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('enterprise_sear...', 'enterprisesearc...')
#19 /ANY_MAGE_HOME_DIR/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#20 /ANY_MAGE_HOME_DIR/app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#21 /ANY_MAGE_HOME_DIR/app/code/core/Mage/Core/Controller/Varien/Action.php(344): Mage_Core_Model_Layout->generateBlocks()
#22 /ANY_MAGE_HOME_DIR/app/code/core/Mage/Core/Controller/Varien/Action.php(269): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#23 /ANY_MAGE_HOME_DIR/app/code/core/Mage/CatalogSearch/controllers/ResultController.php(77): Mage_Core_Controller_Varien_Action->loadLayout()
#24 /ANY_MAGE_HOME_DIR/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_CatalogSearch_ResultController->indexAction()
#25 /ANY_MAGE_HOME_DIR/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#26 /ANY_MAGE_HOME_DIR/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#27 /ANY_MAGE_HOME_DIR/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#28 /ANY_MAGE_HOME_DIR/app/Mage.php(692): Mage_Core_Model_App->run(Array)
#29 /ANY_MAGE_HOME_DIR/index.php(83): Mage::run('', 'store')
#30 {main}";s:3:"url";s:40:"/de-de/catalogsearch/result/?q=blaaaambb";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"de-de";}
```

**Comment by xpoback** [comment]
@tuegeb It would be very good to know the version of magento.

**Comment by tuegeb** [comment]
EE 1.4.2.3
![settings](https://cloud.githubusercontent.com/assets/7773050/16948675/50098ff8-4db6-11e6-89ef-d4a00e78e0d5.png)

**Comment by tuegeb** [comment]
@xpoback: Any news regarding this major issue? Thanks for the feedback.

**Comment by xpoback** [comment]
@tuegeb As seen from the stacktrace, the `Enterprise_Search_Block_Catalogsearch_Layer` is not overwritten and therefore used wrong layer model. 
I tried to reproduce this (with magento 1.14.2.3) but couldn't. If called through `Mage::getModel()` it must be (and normally is)  overriden. It's not clear from the stacktrace how exactly the block was called so the rewrite configuration didn't work.
Without the possibility to recreate the issue I can't debug and fix it for this particular case. 

As for the last screenshot, I added a bit of visualisation for the search engine configuration page. I case of FF it plays no role, but prevents from confusion when FF is enabled, but Mysql was still shown.

**Comment by tuegeb** [comment]
@xpoback: Thanks for the visualisation of the enabled search engine.

The above stated exception is thrown for new search queries. Probably overriding the `Fulltext.php` will help.

**Comment by xpoback** [comment]
@tuegeb Yes, but overwriting the Layer block and model should already exclude `Fulltext` from usage, which actually happens, when the block is succesfully overridden.
Anyways we can overwrite `Fulltext` as well, just for cases like this, when it's not clear why the primary rewrite does not work.

**Comment by tuegeb** [comment]
@xpoback: Ok. Then I suggest that you override the class Fulltext. Thank you in advance.

**Comment by xpoback** [comment]
@tuegeb In the last commit I added some configuration checks, which display warnings on configuration save if any of the blocks or models, which are supposed to be rewritten, are not rewritten or rewritten by another module.

**Comment by tuegeb** [comment]
@tkn98  Could you check this again with the version 4.1.9, please?

**Comment by tkn98** [comment]
Sorry, I'm currently blocked on the issue.

**Comment by xpoback** [comment]
@tkn98 You mean you have no access to it?

**Comment by tkn98** [comment]
Yes, I can't progress, e.g. just upgrade and test on the system I did the report for. Sorry.
