### ISSUE TITLE
sub modules in production automatically disabled

### ISSUE THREAD

**Issue by tuegeb** [Flagbit/Magento-FACTFinder#161]
- FACT-Finder SDK version (see package.xml): 4.1.6

- Magento edition and version: 1.9.2.4 CE OR 1.14.2.3

- PHP version: 7.0.7

- Expected behavior: 
Enabled modules are not automatically disabled.

- Actual behavior: 
In production the following files have suddenly been modified and all sub modules have been disabled.

 /app/etc/modules/FACTFinder_Asn.xml
 /app/etc/modules/FACTFinder_Campaigns.xml
 /app/etc/modules/FACTFinder_Recommendation.xml
 /app/etc/modules/FACTFinder_Suggest.xml
 /app/etc/modules/FACTFinder_TagCloud.xml
 /app/etc/modules/FACTFinder_Tracking.xml

- Steps to reproduce: -
   Suspected method is `FACTFinder_Core_Helper_Data::updateModuleState()`

**Comment by xpoback** [comment]
@tuegeb What is in the settings at Advanced->Disable FACT-Finder Sub-Modules?

**Comment by tuegeb** [comment]
![setting](https://cloud.githubusercontent.com/assets/7773050/16485057/f9ee816c-3ebc-11e6-8bf3-a98388a44a53.png)

**Comment by xpoback** [comment]
@tuegeb I'm not sure we need this feature at all. Evidently, theres an incompatibility in code, when the config values are incorrectly read from files or configuration. 
If we don't need the possibility to disable whole submodules in the backend, we can remove the feature.
For the particular case as a hotfix just comment out the [event here]( https://github.com/Flagbit/Magento-FACTFinder/blob/master/src/app/code/community/FACTFinder/Core/etc/config.xml#L58)

**Comment by tuegeb** [comment]
From my point of view this "feature" is not needed.
