### ISSUE TITLE
Question: replacement of price-slider

### ISSUE THREAD

**Issue by berwa** [Flagbit/Magento-FACTFinder#168]
- FACT-Finder SDK version (see package.xml): 4.1.8
- Magento edition and version: EE1.14.2.3
- FACT-Finder Index Version: 7.1.1

We are currently upgrading one of our customers to FACT-Finder 7.1 and received a lot of negative feedback regarding the "3D-triangle" price-slider.
According to the coordination with Factfinder the 3D-triangle slider is meant to be replaced by a more common one from Fact-Finder 7.1 on.

Are there plannings to replace the price-slider in this Magento SDK? If yes, can you give us an estimate when a more common price-slider will be part of the module?

Thank you in advance

**Comment by xpoback** [comment]
Probably @tuegeb has some information about this.

**Comment by tuegeb** [comment]
@berwa: Who gave you this information?

**Comment by tuegeb** [comment]
@berwa: We will not change the slider template, please follow the instructions on https://github.com/Flagbit/Magento-FACTFinder/wiki/Use-a-different-slider in order to replace the slider template in the project scope.
