### ISSUE TITLE
Saving configuration with error

### ISSUE THREAD

**Issue by dmanners** [Flagbit/Magento-FACTFinder#169]
- FACT-Finder SDK version (see package.xml): 
- Magento edition and version: 1.14.2
- PHP version: 5.5.38
- Expected behavior: Given a reasonable error message telling you what is wrong.
- Actual behavior: Notice: Undefined offset: 1  in app/code/community/FACTFinder/Core/Model/Handler/Status.php on line 298
- Steps to reproduce: Set-up a factfinder account but have an error in the channel name. Then in Magento save the information with the wrong channel name.

Note: during search after you have saved with the incorrect channel you will see the following in the error logs. de.factfinder.security.exception.ChannelDoesNotExistException: Channel 'it-test' does not exist. So it appears that factfinder knows the channel does not exist but the Magento module does not seem to pick this up on configuration save.

**Comment by xpoback** [comment]
@dmanners Thank you! The fix in now in master and will be live within the next release.
