### ISSUE TITLE
Italian breaks the autosuggest box

### ISSUE THREAD

**Issue by dmanners** [Flagbit/Magento-FACTFinder#170]
- FACT-Finder SDK version (see package.xml): 
- Magento edition and version: 1.14.2
- PHP version: 5.5/5.6
- Expected behavior: Autosuggest should work in all languages
- Actual behavior: Javascript error when loading a page with the search box on.
- Steps to reproduce: Using Italian and the standard Magento language pack load any page with the suggest box on and you will see a JS error cause by the file `factfinder/suggest/advancedsuggest.phtml`. This is because "Search entire store here..." is translated to "Cerca nell'intero negozio...". This causes a JS error as the ' inside the string is not escaped when being used in the JS for the search form.

**Comment by xpoback** [comment]
@dmanners The fix is currently available in master and will be included in the next release.

**Comment by xpoback** [comment]
The fix is available since 4.1.9
