### ISSUE TITLE
Turning off after search navigation

### ISSUE THREAD

**Issue by dmanners** [Flagbit/Magento-FACTFinder#171]
- FACT-Finder SDK version (see package.xml): 4.1.9
- Magento edition and version: 1.14.2
- PHP version: 5.5/5.6
- Expected behavior: When I turn off the ASN from Factfinder I should still see the ASN from magento default.
- Actual behavior: I see no filters at all.
- Steps to reproduce: Turn off the ASN from the Factfinder module and visit a search page. It seems the function `removeLayerFilters` does not currently check if ASN is enable and will just always reset filters. Is there a reason behind this that I am missing?

**Comment by xpoback** [comment]
@dmanners This is intentional, since Magento filters often don't correspond with the data returned from FF. Integration of default Magento filters and FF search results was not implemented. 
So at the moment there's are two options, if FF search engine is enabled: either ASN or no filters at all.

**Comment by dmanners** [comment]
Ah thank you for the information. I thought this would have something to do with it but I just wanted to double check.
