### ISSUE TITLE
Cron check for already running exports

### ISSUE THREAD

**Issue by hollymurdoch** [Flagbit/Magento-FACTFinder#174]
- SDK 4.1.9
- Magento CE 1.9.1

Issue
Product, stock & price export script do not determine whether the script is already running, before triggering again. This results in multiple instances trying to write to the same file.

Resolution
Add step to script whereby a check is first made to see if there is already a running script. If yes, do not run script again. If not, run script.

**Comment by tuegeb** [comment]
@xpoback: The known locking https://github.com/Flagbit/Magento-FACTFinder/blob/master/src/app/code/community/FACTFinder/Core/controllers/ExportController.php#L172 should also be applied on the Magento cron job + CLI export.

**Comment by xpoback** [comment]
Semaphore has been added.
