### ISSUE TITLE
Expression passed as references (Log-Spam)

### ISSUE THREAD

**Issue by Shadowsvoices** [Flagbit/Magento-FACTFinder#176]
The following function contains code that passes a expression by reference which triggers PHP Strict warnings: 

**FACTFinder_Core_Helper_Export#getExportImageWidth()**
``` php
$width = array_shift(explode('x', $width));
```

This is not a major issue but a quick and easy fix.

Array Shift Signature:
``` php
function array_shift (array &$array) {}
```

Suggested Fix: Save result in temporary variable
``` php
$width = explode('x', $width);
$width = array_shift($width);
```

**General Issue Info**:
- FACT-Finder SDK version (see package.xml): 4.1.9 (latest master branch at time of issue creation)
- Magento edition and version: 1.9.2.x
- PHP version: 5.6.x
- Expected behavior: no strict warning log messages
- Actual behavior: lots of strict warning log messages
- Steps to reproduce: set PHP error_reporting to -1 and run export cron

**Comment by xpoback** [comment]
Thank you!

**Comment by Shadowsvoices** [comment]
No problem, I created a few more like those :)
