### ISSUE TITLE
"Invalid Argument supplied for foreach" Log-Spam

### ISSUE THREAD

**Issue by Shadowsvoices** [Flagbit/Magento-FACTFinder#177]
Log messages occur when data tracking is prepared due to (most likely) non-object being used. 
Easily fixed by including a if-check as the data might actually be empty / null.

**Log messages sample:**
```
2016-09-05T08:37:18+00:00 ERR (3): Warning: Invalid argument supplied for foreach()  in /xxx/modules/Magento-FACTFinder/src/app/code/community/FACTFinder/Tracking/Block/Abstract.php on line 48
2016-09-05T08:37:18+00:00 ERR (3): Warning: Invalid argument supplied for foreach()  in /xxx/modules/Magento-FACTFinder/src/app/code/community/FACTFinder/Tracking/Block/Abstract.php on line 30
```

**Class: FACTFinder_Tracking_Block_Abstract***
Line 43-53
``` php
public function getJsonDataObject()
    {
        $dataTemplate = $this->getDataTemplate();

        $data = array();
        foreach($this->getProductResultCollection() as $product){
            $data[$product->getId()] = $this->getProductData($product) + $dataTemplate;
        }

        return Mage::helper('core')->jsonEncode($data);
    }
```

**Class: FACTFinder_Tracking_Block_Abstract***
Line 43-53
``` php
public function getJsonUrlToIdMappingObject()
    {
        $data = array();
        foreach($this->getProductResultCollection() as $product){
            $data[$product->getProductUrl()] = $product->getId();
        }

        return Mage::helper('core')->jsonEncode($data);
    }
```

**Possible fix:**
Include a if-check before iterating over the collection.
Note: Only tested on development/staging so far, not live.
``` php
if(is_array($collection) || $collection instanceof Traversable)
```

- FACT-Finder SDK version (see package.xml): 
- Magento edition and version: 1.9.2.x
- PHP version: 5.6.x
- Expected behavior: no log messages 
- Actual behavior: log messages
- Steps to reproduce: unclear, happens sporadically on frontend requests possibly due to empty recommendation or filters on some pages

**Comment by xpoback** [comment]
Thank you for reporting. Even though I couldn't reproduce the issue, the fix I added should fix it, since there was no check if the method returns the value specified in the PHPDoc.

**Comment by Shadowsvoices** [comment]
I've fixed it this way to, my guess is it happens when some requests to the FF server run into a timeout (causes the json_decode exception mentioned in #160 ) as the log timestamps seem to very closely related
