### ISSUE TITLE
Exports shouldn't write to current file

### ISSUE THREAD

**Issue by Shadowsvoices** [Flagbit/Magento-FACTFinder#178]
When running the export process the "new" file is written directly over the old file.
When the file is read at that time the reader would get a incomplete/faulty state.

A more cautious approach would be to write the new data to a temporary file, for example using uniqid() or time():
``` store_1_product.csv.tmp57cd47f10700e ```
And then renaming it to the new file (which is an atomic operation at least on Unix while on the same FS):
``` php 
bool rename ( string $oldname , string $newname [, resource $context ] )
```

This would allow you to skip locking for download requests and ensure that there will never be an incomplete file being served, even for unforeseeable circumstances like the process executing the job dying.

- FACT-Finder SDK version (see package.xml): n/a
- Magento edition and version: n/a
- PHP version: n/a
- Expected behavior: n/a 
- Actual behavior: n/a
- Steps to reproduce: n/a

**Comment by xpoback** [comment]
Thank you for this great idea, it will be a nice supplement for #174

**Comment by hollymurdoch** [comment]
Agreed, this would be a very useful improvement

**Comment by tuegeb** [comment]
It's a known requirement: #152
