### ISSUE TITLE
Recommendation Order does not match Demo Shop

### ISSUE THREAD

**Issue by Shadowsvoices** [Flagbit/Magento-FACTFinder#183]
Recommendation products are not ordered correctly in Magento, they are ordered by Magento internal position field. 

The first order condition is applied before the second condition, therefor the second condition only works if the Magento position field is identical (which it is not in most cases).
See sample query:
``` sql
ORDER BY `position` ASC,
find_in_set(`e`.`entity_id`, '7316,7317,7217,7216,7215,7207,7210,7224,7208,7223')
```

Expected query after fix:
``` sql
ORDER BY find_in_set(`e`.`entity_id`, '7532,7544,7542,7541,7543,7540,7487,7246,7317,7537')
```

This can easily be fixed by resetting the previously applied order statements using Zend_Db_Select's class functionality:

**FACTFinder_Recommendation_Model_Observer#_processCollection()**
**Line: 100-108**
``` php
...
if ($recommendations) {
    $collection->addAttributeToFilter($idFieldName, array('in' => $recommendations));

    $order = new Zend_Db_Expr($collection->getConnection()->quoteInto(
        'find_in_set(`e`.`' . $idFieldName . '`, ?)',
        implode(',', $recommendations)
    ));
    $select->reset(Zend_Db_Select::ORDER); // ensure sort order is only determined by FF
    $select->order($order);
} else {
...
```

- FACT-Finder SDK version (see package.xml): 4.1.9
- Magento edition and version: 1.9.2.4 
- PHP version: 5.6.x
- Expected behavior: Products should be in the same order as provided by FF 
- Actual behavior: Products are not sorted accordingly
- Steps to reproduce: 
  1. Install/Configure recommendation
  2. Compare recommendation results in FF Demo Shop with Magento Shop
  3. Products are correct, but order does not match

**Comment by xpoback** [comment]
@Shadowsvoices Thank you for your contribution. Your change will be included to the next release and is already in master.
