### ISSUE TITLE
Autoloader loads Tracking Helper with wrong path

### ISSUE THREAD

**Issue by lmandes** [Flagbit/Magento-FACTFinder#185]
- FACT-Finder SDK version (see package.xml): 4.1.1
- Magento edition and version: CE 1.9.2.4
- PHP version: 5.5.9
- Expected behavior: 
- Actual behavior: 
this file Tracking/Helper/Data.php was loaded from Magento Core and not from FACTFinder module in community folder; see attached txt file for more informations
- Steps to reproduce: 

[FF_error.txt](https://github.com/Flagbit/Magento-FACTFinder/files/576112/FF_error.txt)

**Comment by xpoback** [comment]
@lmandes Has the problem been resolved? Looks like the file was just not found.

**Comment by lmandes** [comment]
Hi xpoback,

no, the problem is still on but I have uploaded an old version of FF and now it's ok
I think the problem is caused by FF loader but I can't reproduce it because it happens without a reason; all models, blocks, helpers, etc. has loaded correctly expect this one

now I have another problem but I open another issue

thank you for reply

**Comment by tuegeb** [comment]
Could be related to #179

**Comment by lmandes** [comment]
I think it's not the same error; issue 179 loads another extension (AOE_Scheduler) and tells about cron context
I recognize that it's impossible to reproduce the error so I close the issue
I'll open it if I find more details
