### ISSUE TITLE
No match between Suggest result and js parser

### ISSUE THREAD

**Issue by lmandes** [Flagbit/Magento-FACTFinder#186]
- FACT-Finder SDK version (see package.xml):  4.0.9
- Magento edition and version:  CE 1.9.2.4
- PHP version: 5.5.9
- Expected behavior: 
- Actual behavior: 
- Steps to reproduce: 

the url called is like this
http://search68.fact-finder.de/Buffetti/Suggest.ff?channel=it&query=carta&format=JSONP&jquery_callback=jXHR.cb4&callback=jXHR.cb4

the result contains only category items and must be parsed through suggest e jXHR js files.
In suggest.js the method loadDataCallback parses results searching "item.searchParams" or "item.channel" but these elements are not incorporated then the call goes to the exception in "ThrowError" function.

I attach two js files
[factfinder.zip](https://github.com/Flagbit/Magento-FACTFinder/files/578896/factfinder.zip)

**Comment by tuegeb** [comment]
@lmandes: This module officially supports only FACT-Finder >= 6.9 (see: https://github.com/Flagbit/Magento-FACTFinder/blob/master/package.xml#L14). Previous versions have a different suggest API and will not be supported.

**Comment by lmandes** [comment]
After many searches I found my FF version and maybe it's 6.6
which module version may I download according to mine?
