### ISSUE TITLE
Static fields: created_at, udpated_at in backend selectable, but not exported

### ISSUE THREAD

**Issue by c21tobias** [Flagbit/Magento-FACTFinder#190]
- FACT-Finder SDK version (see package.xml): 4.1.11
- Magento edition and version: 1.9.2.4
- PHP version: 7.0
- Expected behavior: 
Fields like created_at and udpated_at are selectable to be exported and expected to be exported to the product feed.
- Actual behavior: 
created_at and udpated_at are empty in the exported product-feed.
- Steps to reproduce: 
Add created_at to list of exported attributes and generate product feed.

**Comment by xpoback** [comment]
This was fixed in the development branch and will be included in the next release.
