### ISSUE TITLE
Missing Parameter for delimeter in fgetcsv (Core/Model/File/Validator/Abstract.php:125)

### ISSUE THREAD

**Issue by rootfuchs** [Flagbit/Magento-FACTFinder#193]
- FACT-Finder SDK version (see package.xml):  2
- Magento edition and version:  Magento Enterprise - Version 1.14.0.1 
- PHP version:  PHP 5.6.29-0+deb8u1

- Expected behavior: 
After export  - with an non default field delimiter -  the temporary files should be finalized and renamed.

- Actual behavior: 
After export - with an non default field delimiter - the temporary files were deleted and an exception with EXCEPTION_SIZE_MISMATCH thrown. 

- Steps to reproduce: 
Export with non default field delimiter. Semicolon(;) instead of comma (,).

Fix:
In Core/Model/File/Validator/Abstract.php:125 the fgetcsv has no parameter for the delimiter given.
The Line should be adjusted to use $this->getCsvDelimiter() as in Line 59.

**Comment by xpoback** [comment]
The fix will be released in the next version.
