### ISSUE TITLE
'Undefined Index' Notice when searching

### ISSUE THREAD

**Issue by NathMorgan** [Flagbit/Magento-FACTFinder#195]
- FACT-Finder SDK version (see package.xml): 4.1.11
- Magento edition and version: EE:1.14.2.2
- PHP version: 5.4.45
- Expected behavior: Display search results without a error
- Actual behavior: Displays a 'Notice: Undefined index: p' message on the page
- Steps to reproduce: Searching with display errors set to ALL

From looking at the code it seems to be coming from FACTFinder_Core/Block/Catalog/Pager.php on line 73 `$pageNum = $params['p']` changing this to `$pageNum = isset($params['p']) ? $params['p'] : 0;` resolves this issue

**Comment by xpoback** [comment]
@NathMorgan Thank you for your contributiion.
