### ISSUE TITLE
Export problem for searchable attributes in v4.1.13

### ISSUE THREAD

**Issue by homecoded** [Flagbit/Magento-FACTFinder#199]
- Extension-Version: v4.1.13
- Magento edition and version: 1.14.3.2 EE
- PHP version: 5.6.30
- Expected behavior: 

CSV-Export contains the same attributes as in version v4.1.12

- Actual behavior: 

CSV-Export is missing searchable attributes

- Steps to reproduce: 

I made an CSV-export with version v4.1.12. Then, I upgraded the Magento-FACTFinder extension and compared the results. I saw that all user-defined searchable attributes were missing from the ```searchable_attributes``` column in the CSV. So, I browsed through the code and in ```app/code/community/FACTFinder/Core/Model/Export/Type/Product/Attribute.php``` I found the method ```_isAttributeSearchable```, which may be be faulty:

```
    protected function _isAttributeSearchable($attribute, $storeId)
    {
        if ($this->_isAttributeNumerical($attribute, $storeId)) {
            return false;
        }

        if (!$attribute->getIsUserDefined()
            || !$attribute->getIsSearchable()
            || in_array($attribute->getAttributeCode(), $this->getExportAttributes($storeId))
        ) {
            return true;
        }

        return false;
    }
```
Because of the ```!$attribute->getIsSearchable()```expression, the method will not return true for user-defined attributes even if they are searchable. In our code, I went ahead an overrode ```FACTFinder_Core_Model_Export_Type_Product_Attribute``` and replaced the ```_isAttributeSearchable``` method with a version where the ```!``` is missing in front of ```$attribute->getIsSearchable()```. Then, the export produced exactly the same results as in version v4.1.12.

If indeed you agree that is is a mistake, I am happy to propose a PR.

**Comment by DennisU** [comment]
Hi homecoded,

you can make a PR in banch develop. I will check your PR next week.

**Comment by homecoded** [comment]
Hi DennisU, here you go https://github.com/Flagbit/Magento-FACTFinder/pull/200

**Comment by homecoded** [comment]
Merged by maintainer. Thanks!
