### ISSUE TITLE
Add to Cart - Tracking: Quantity isn't tracked correctly

### ISSUE THREAD

**Issue by M-arcus** [Flagbit/Magento-FACTFinder#210]
- FACT-Finder SDK version (see package.xml): Release 4.1.13
- Magento edition and version: Magento 1.9 Community
- PHP version: 5.5.9
- Expected behavior:
When adding a configurable Product to the cart, the [FACTFinder_Tracking_Model_Observer](https://github.com/Flagbit/Magento-FACTFinder/blob/master/src/app/code/community/FACTFinder/Tracking/Model/Observer.php) should track the correct count and transfer it to FactFinder.
- Actual behavior: 
This [code](https://github.com/Flagbit/Magento-FACTFinder/blob/master/src/app/code/community/FACTFinder/Tracking/Model/Observer.php#L85) always returns 1. 
- Steps to reproduce: Add a configurable product to the cart with more than 1 quantity.

Hotfix:

Use `$qty = (Int)$observer->getProduct()->getQty();` instead of `$qty = $quoteItem->getQty();` on [line 85](https://github.com/Flagbit/Magento-FACTFinder/blob/master/src/app/code/community/FACTFinder/Tracking/Model/Observer.php#L85).

**Comment by DennisU** [comment]
Thank you, i will check this and inform you after I checked.

**Comment by M-arcus** [comment]
Since https://github.com/Flagbit/Magento-FACTFinder/pull/211 got merged, you can close this issue
