### ISSUE TITLE
Feature Request: Add Product Identifier Field for Recommendation

### ISSUE THREAD

**Issue by M-arcus** [Flagbit/Magento-FACTFinder#214]
Please add a configuration field for setting a Product identifier specifically for the Recommendation.

There is currently the problem that if you use a different identifier for Suggest and Recommendation, one of them is not going to work

![image](https://user-images.githubusercontent.com/25648755/28680143-c121f8aa-72f5-11e7-8556-099a7ecfad43.png)
(after Tracking Product Identifier)

**Comment by mbraeuner** [comment]
This issue was fixed on develop by [PR 25](https://github.com/Flagbit/Magento-FACTFinder/pull/215) ad has been merged into master today
