### ISSUE TITLE
Hardcoded exclude of Status and visibility

### ISSUE THREAD

**Issue by ckapitzke** [flagbit/Magento-FACTFinder#221]
- FACT-Finder SDK version (see package.xml):  4.1.14

Hey there,
i'd like to ask why the system attributes "status" and "visibility" are excluded from the export?

is there any reason?

See FACTFinder_Core_Model_Export_Type_Product_Attribute::addAttributesToRow Line 480

best,
christian

**Comment by mbraeuner** [comment]
I did not find a specification for that, yet. Usually a product has to be active and visible to be exported. Both should be true. Do you have a reason or a need to export them? Maybe for configurable products and their simple children?

**Comment by ckapitzke** [comment]
Exactly. If i export configurable products and their children, the suggest call replies sometimes the child products which are not visible by default and clicking on the "view product" Link results in a 404 page. so if i export status and visibility i can configure a down ranking for these products

**Comment by mbraeuner** [comment]
Usually the child products should show the configurables. FACT-Finder will connect the childs with partens via the parent_id relation.
The link which leads to a 404 page, does it include something like "factfinder.php"? We found a strange bug, where magento adds this to the product url, if you export the product by cronjob.
Can you provide me the link to your shop, please? I'll have a look at this.
