### ISSUE TITLE
FACTFinder Tracking issues and error in log files.

### ISSUE THREAD

**Issue by mrPrabhat** [Flagbit/Magento-FACTFinder#223]
- FACT-Finder SDK version (see package.xml): 
- Magento version:  1.9.2.1
- PHP version: 5.6.36
- Expected behavior: No warnings on factfinder dashboard and no errors in log files 
- Actual behavior: We are getting three warnings :
Unusual distribution of interest tracking: 127 clicks > 387 carts > 122 checkouts
No recommendation clicks were found.
No ASO data is available.
and in log files we are getting 2 errors
1.  2018-06-01T01:49:15+00:00 DEBUG (7): INFO: Request Url: https://duffydiscount.fact-finder.co.uk:443/duffydiscount/Search.ff?filtersearchable_attributes=Silver&filterwidth=%5BVALUE%5D&followSearch=9201&sortavailable_in_store=asc&sortrelevance=asc&sortwidth=asc&verbose=true&query=garage%20racking&productsPerPage=16&channel=uk-live&idsOnly=true&page=1&sid=b36ce6e14f53f9df3c7590841a22d606&format=json&timestamp=1527817755000&username=shopUser&password=30cec3210933093c1885e028a3b47146
2018-06-01T01:49:15+00:00 DEBUG (7): ERROR: Connection failed. HTTP code: 500
2018-06-01T01:49:15+00:00 DEBUG (7): ERROR: FACT-Finder returned error: A server error with the code 500 has occurred.Please contact the site operator. Please record and report the exact web address (URL) and the following server time: Friday, June 1, 2018 3:49:16 AM CEST.
2018-06-01T01:49:15+00:00 DEBUG (7): ERROR: Stacktrace:
java.lang.NumberFormatException: For input string: "[VALUE]"
  at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
  at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
  at java.lang.Double.parseDouble(Double.java:538)
  at de.factfinder.search.Search.applyFilter(Search.java:1550)

2. 2018-05-31T05:40:02+00:00 DEBUG (7): ERROR: Export action exception 'Mage_Core_Exception' with message 'exception 'Exception' with message 'Unsupported image format.' in /home/rackzone/public_html/lib/Varien/Image/Adapter/Gd2.php:233

What i have already tried:-
1. I have removed [VALUE] from the code at my end.
   Initially this error didn't show up but today it is again coming.

Please guide me to fix this.

**Comment by mbraeuner** [comment]
It seems to be a templates problem. The layerd nav Sliders are not working properly. There are two requests for every change. The second one is the one of FF extension. It delivers emtpy values.

![auswahl_685](https://user-images.githubusercontent.com/29225156/40963816-c495a540-68a9-11e8-9b0c-173eae8e295b.png)

Inside slider.phtml there is a replacement of "%5BVALUE%5D" to the left and right range of the slider.
This piece of code is missing at your catalog page https://github.com/Flagbit/Magento-FACTFinder/blob/73061d7e6dbb1935b9e288bda513b125c042dd87/src/app/design/frontend/base/default/template/factfinder/asn/layer/filter/slider.phtml#L22
Have look if something overwrites this template.

**Comment by mrPrabhat** [comment]
below is my slider.phtml. Please guide me where i am wrong

<?php
/**
 * FACTFinder_Asn
 *
 * @category Mage
 * @package FACTFinder_Asn
 * @author Flagbit Magento Team <magento@flagbit.de>
 * @copyright Copyright (c) 2016, Flagbit GmbH & Co. KG
 * @license https://opensource.org/licenses/MIT  The MIT License (MIT)
 * @link http://www.flagbit.de
 */
/**
 * Slider HTML Template
 */
?>
<?php
$height_default_min = Mage::getStoreConfig('shelfslidersettings/shelfslidersettings/height_min_range', Mage::app()->getStore());
$height_default_max = Mage::getStoreConfig('shelfslidersettings/shelfslidersettings/height_max_range', Mage::app()->getStore());
$slider_step = Mage::getStoreConfig('shelfslidersettings/shelfslidersettings/slider_steps', Mage::app()->getStore());
$currency_code = Mage::app()->getStore()->getCurrentCurrencyCode();
$currency_symbol = Mage::app()->getLocale()->currency( $currency_code )->getSymbol();
?>
<ol style="margin: 10px;">
    <?php foreach ($this->getItems() as $_item): $uniqued = rand() . time(); 
		$filter_name = strtolower($_item->getName());
    ?>
        <li>
            <div id="<?php echo $filter_name.'_filter_slider'; //base64_encode($this->getData('requestVar')); ?>" style="width: 100%;padding:10px 0px;"></div>
            
            <?php  if($filter_name == 'price'){
				$slider_step = 5;
			?>	<span class="min filter_<?php echo $filter_name ?>"><?php echo $currency_symbol; ?><?php echo $this->getSelectedMin(); ?></span>
				<span class="max filter_<?php echo $filter_name ?>"><?php echo $currency_symbol.$this->getSelectedMax(); ?></span>
			<?php } else { ?>
				<span class="min filter_<?php echo $filter_name ?>"><?php echo $this->getSelectedMin(); ?></span>
				<span class="max filter_<?php echo $filter_name ?>"><?php echo $this->getSelectedMax(); ?></span>
			<?php } ?>	
            <script type="text/javascript" language="javascript">
                //<![CDATA[
                jQuery(function () {
					jQuery("#<?php echo $filter_name.'_filter_slider'; //echo base64_encode($this->getData('requestVar'));?>").slider({
						range: true,
						step: <?php echo $slider_step; ?>,
						min: 0<?php //echo $this->getSelectedMin(); ?><?php //echo $height_default_min; ?>,
						max: <?php //echo $this->getSelectedMax(); ?><?php echo $height_default_max; ?>,
						animate: "fast",
						values: [<?php echo $this->getSelectedMin(); ?>, <?php echo $this->getSelectedMax(); ?>],
						 create: function () {
							jQuery('.min.filter_<?php echo $filter_name ?>').appendTo(jQuery('#<?php echo $filter_name.'_filter_slider'; ?> .ui-slider-handle').get(0));
							jQuery('.max.filter_<?php echo $filter_name ?>').appendTo(jQuery('#<?php echo $filter_name.'_filter_slider'; ?> .ui-slider-handle').get(1));
						},
						slide: function (event, ui) {
							<?php  if($filter_name == 'price'){	?>	
							jQuery(ui.handle).find('span').html('<?php echo $currency_symbol; ?>' + ui.value);
							<?php } else { ?>
							jQuery(ui.handle).find('span').html('' + ui.value);
							<?php } ?>
							/* Prevent values overlap */
							if(parseInt(ui.values[0]) > 5500){
								var htMinLeft = ((ui.values[0]/100)%4)*50;
								if(ui.values[0] >= 5500) htMinLeft = 210;
								if(ui.values[0] >= 6900) htMinLeft = 250;
								jQuery('.min.filter_<?php echo $filter_name ?>').css('left', '-'+htMinLeft+'%');
							}else{
								jQuery('.min.filter_<?php echo $filter_name ?>').removeAttr('style');
							}
							
							if(parseInt(ui.values[1]) < 100){
								var htMaxLeft = 200;
								//if(ui.values[1] <= 300) htMaxLeft = 140;
								if(parseInt(ui.values[1]) <= 100) htMaxLeft = 210;
								if(parseInt(ui.values[1]) == 0) htMaxLeft = 230;
								jQuery('.max.filter_<?php echo $filter_name ?>').css('left', htMaxLeft+'%');
							}else{
								jQuery('.max.filter_<?php echo $filter_name ?>').removeAttr('style');
							}
							/* Prevent values overlap Ends */
						},
						stop: function( event, ui ) {
							
							var price = jQuery( "#price_filter_slider" ).slider( "values" );
							var height = jQuery( "#height_filter_slider" ).slider( "values" );
							var width = jQuery( "#width_filter_slider" ).slider( "values" );
							var depth = jQuery( "#depth_filter_slider" ).slider( "values" );
							
							var filterCategoryROOT = '';
							var fieldQ = 'filtercategoryROOT=';
							var currentUrl = window.location.href;
							if(currentUrl.indexOf('?' + fieldQ) != -1){
								filterCategoryROOT = currentUrl.split(fieldQ)[1];
								filterCategoryROOT = '&'+fieldQ+filterCategoryROOT.split('&')[0];
							}
							var url = '<?php echo Mage::getBaseUrl().'catalogsearch/result/index/?q='.urlencode($this->getRequest()->getParam('q')); ?>'+filterCategoryROOT+'&filterPrice='+price[0] + ' - ' + price[1]+'&filterheight='+height[0] + ' - ' + height[1]+'&filterwidth='+width[0] + ' - ' + width[1]+'&filterdepth='+depth[0] + ' - ' + depth[1]+'&limit=16&verbose=true';
							console.log(url);
							jQuery('#factfinder_filter_url').attr('href', url);
							var _url = '<?php echo $_item->getUrl() ?>';
							console.log(_url);
						}
					});
				});	
               
                //]]>
            </script>
        </li>
    <?php endforeach ?>
</ol>

**Comment by mbraeuner** [comment]
The problem problem seems to be, that you templates builds a different url functionality. Yo do not have to build the url from scratch. Please have a look into the default template of this module. Use this two lines of code to change the url in your "stop" method of the slider. 
[modules code](https://github.com/Flagbit/Magento-FACTFinder/blob/73061d7e6dbb1935b9e288bda513b125c042dd87/src/app/design/frontend/base/default/template/factfinder/asn/layer/filter/slider.phtml#L31):
`var url = '<?php echo $_item->getUrl() ?>';`
`window.location.href= url.replace('%5BVALUE%5D',left + ' - ' + right);`

and replace the "left" and "right" with the values of the slider. If this works you can add additional parameters, if needed.

**Comment by mbraeuner** [comment]
did you manage it?
