### ISSUE TITLE
Incompatibility with manadev Filter

### ISSUE THREAD

**Issue by maxcamo** [Flagbit/Magento-FACTFinder#224]
- FACT-Finder SDK version (see package.xml): 
- Magento edition and version: 1.9.2.0
- PHP version: 5.6
- Expected behavior: In the result page we must see the filter column from factfinder integrated with the manadev module
- Actual behavior: in the result page of a seearch we can't implement the filter column 
- Steps to reproduce: 
We are using manadev filter to manage better the filter of Magento, If we install the factFinder module we can't show the filter bar on the result search page.

Can u help us to fix and implement that module?

**Comment by mbraeuner** [comment]
Mana Filter is database driven. The FACT-Finder module loads filters, attributes and their option values from FACT-Finders API. I did not have a very deep look into it, but Mana loads the values from its own database tables. The model of Mana seems to be its key feature. 
If you want to combine both, you have to overwrite Manas model with the FACT-Finder model. 
I think it is easier to use the FACT-Finder module and set up filters with multiple options with FACT-Finder server. 
What is the key feature you are missing without Mana? Do you need multiple selection of attribute options?

**Comment by mbraeuner** [comment]
Did you manage it? Development of a Mana integration will not be part of free service here on github. Don't hastiate to contact our development teams for integrating special solutions for you https://www.flagbit.de/kontakt.html
