### ISSUE TITLE
 Call to a member function getUrl() on a non-object

### ISSUE THREAD

**Issue by RidRack** [flagbit/Magento-FACTFinder#227]
Hi, 

I've found a bug in the Magento Factfinder code which I believe is causing an exception further down the line:

```
E_ERROR: Call to a member function getUrl() on a non-object
in FACTFinder_Core_Block_Catalog_Product_List_Toolbar::initSortings called at app/code/community/FACTFinder/Core/Block/Catalog/Product/List/Toolbar.php (367)
in FACTFinder_Core_Block_Catalog_Product_List_Toolbar::initSortings called at app/code/community/FACTFinder/Core/Block/Catalog/Product/List/Toolbar.php (92)
in FACTFinder_Core_Block_Catalog_Product_List_Toolbar::getPagerUrl called at app/code/core/Mage/Catalog/Block/Product/List/Toolbar.php (483)
```

The issue looks to be caused by there being no null check on the `$sorting` variable before `$sorting->getUrl()` is called, which further down causes this issue. The code in question can be found here:

https://github.com/Flagbit/Magento-FACTFinder/blob/25e53762abc0efb8606a8ad7f5784ef10c051a48/src/app/code/community/FACTFinder/Core/Block/Catalog/Product/List/Toolbar.php#L369

Could you please resolve this so that I stop getting an exception thrown? 

Thanks

**Comment by mbraeuner** [comment]
I had a look into it. We can chage the code. But I try to find out how to reproduce. Because I want to fix the root cause. Did you change it locally in your code to get it to work?

**Comment by RidRack** [comment]
Hi @mbraeuner , 

I've not been able to reproduce it consistently, but it's still been occurring. Regardless, it's still a bug.

**Comment by mbraeuner** [comment]
I can't reproduce it on my setup. So I can not fix the root cause in depth. I fixed only the negative effect of throwing errors for you. Please have try and let me know, if it works for you [branch issue-227](https://github.com/flagbit/Magento-FACTFinder/tree/issue-227)

**Comment by RidRack** [comment]
@mbraeuner , looks like this would solve it, so I'll close the issue. In my code I just checked for whether or not the object was there before using, but your code is more thorough.
