### ISSUE TITLE
Filter drop-down box not yet implemented

### ISSUE THREAD

**Issue by Thaldos** [Flagbit/Magento-FACTFinder#229]
Hello,

- FACT-Finder SDK version (see package.xml): 4.2.0
- Magento edition and version: 1.11.2 Enterprise
- PHP version: 7.2.8
- Expected behavior: 
In this documentation page https://github.com/Flagbit/Magento-FACTFinder/wiki/ASN-customization, you said that "_all elements that exceed this value will be shown in a drop-down box._". 
- Actual behavior: 
But to render the filters elements, the template used by default is "catalog/layer/filter.phtml". And in "catalog/layer/filter.phtml", nothing is implemented to handled a "drop-down box" system.

So I would know if this "drop-down box" have been done somewhere else, or it is not yet implemented ?

Thanks a lot

**Comment by mbraeuner** [comment]
Sorry, you are right. It's not implemented. Output is done by your templates and this extension does not provide or overwrite filter.phtml. I think it was featured by some templates former days. I'll change the documentation.
