### ISSUE TITLE
Singe word search

### ISSUE THREAD

**Issue by testBanana** [Flagbit/Magento-FACTFinder#231]
- FACT-Finder SDK version (see package.xml): 4.1.13
- Magento edition and version: 1.9.1.1
- PHP version: 5.6
- Expected behavior: 
- Actual behavior: 
- Steps to reproduce: 

i have activated the module "Single word search", but i can't activate this module in Magento. 
Is there posibility to use this module in Magento?

**Comment by mbraeuner** [comment]
Can you explain in details, please? Why do you think that activation of module "Single word search" depends on this FACT-Finder Extension? Do you get any releated errors?

**Comment by mbraeuner** [comment]
"Single word search" is a FACT-Finder back end preference and works automaticall.
