### ISSUE TITLE
getLimitUrl return empty string

### ISSUE THREAD

**Issue by jackjackde** [flagbit/Magento-FACTFinder#233]
- FACT-Finder SDK version (see package.xml): 4.2.0
- Magento edition and version:  1.14.3.9
- PHP version: 5.6.38
- Expected behavior: When select a page limit, the displayed products will updated to selected limitation (e.g. 12, 24, 36)
- Actual behavior: Reload site without limitation, getLimitUrl return empty string ( in template/page/html/pager.phtml), select options has no values 
- Steps to reproduce: 
Visit catalogsearch/result/?q=[insert query for your products], change limitation to another value. 

The values for the limitation are set at FactFinder Backend.

```
// template/page/html/pager.phtml
<?php echo $this->getLimitUrl($_key) ?>
```
```
// FACTFinder_Core_Block_Catalog_Product_Pager
public function getPagerUrl($params = array())
    {
        if (!$this->getPaging()) {
            return parent::getPagerUrl($params);
        }
        $pageNum = (isset($params['p']) ? $params['p'] : 0);
        if (!isset($this->_pagingUrls[$pageNum])) {
            $this->_pagingUrls[$pageNum] = '';
            /** @var \FACTFinder\Data\Page $pageItem */
            foreach ($this->getPaging() as $pageItem) {
                if ($pageItem->getPageNumber() == $pageNum) {
                    $this->_pagingUrls[$pageNum] = $pageItem->getUrl();
                    break;
                }
            }
        }

        return $this->_pagingUrls[$pageNum];
    }
```
it seems this method ignore other page url paramter like limit, ...

**Comment by mbraeuner** [comment]
I testet the limitation part. I think, I do not understand your problem correctly. 
I setup a fresh magento demo store. Setup page limitation to some limits in FACT-Finder Backend, activated "Use results per page options" in Magento. 
I requested catalogsearch/result/?q=[insert query for your products] and changed the limitation. What is not working on the page at this step?

The Urls are delivered by the $pageItem->getUrl() and they should include the current limit parameter. This URLs are delivered by factfinder API. If I use limitation parameter or delete it, does not matter. 

Did you activate the "Use results per page options" in Magento FF Extension?

**Comment by jackjackde** [comment]
Ich hoffe, es ist okay, wenn ich auf deutsch weiter mache...
Ob die Funktion zur Nutzung der FF Limitierung nun aktiv ist oder nicht, sie liefert ein leeres Ergebnis. Die Original Funktion "getPagerUrl", welche aufgerufen werden soll, wenn das FF Modul deaktiviert ist, greift nicht und der darauf folgende Block ignoriert den übergebenen limit Parameter.

```
// src/app/code/community/FACTFinder/Core/Block/Catalog/Product/Pager.php
    public function getPagerUrl($params = array())
    {
        if (!$this->getPaging()) {
            return parent::getPagerUrl($params); // wird nicht aufgerufen, wenn FF Modul aktiviert ist
        }

        $pageNum = (isset($params['p']) ? $params['p'] : 0);

        if (!isset($this->_pagingUrls[$pageNum])) {
            $this->_pagingUrls[$pageNum] = '';
            /** @var \FACTFinder\Data\Page $pageItem */
            foreach ($this->getPaging() as $pageItem) {
                if ($pageItem->getPageNumber() == $pageNum) {
                    $this->_pagingUrls[$pageNum] = $pageItem->getUrl();
                    break;
                }
            }
        }

        return $this->_pagingUrls[$pageNum];
    }

```
`$pageItem->getPageNumber()` liefert als erstes eine 1 und vergleicht mit `$pageNum`, welches 0 ist. 
Zudem liefert `$pageItem->getUrl()` lediglich die Paginierung, jedoch keine Limitierung, obwohl im Funktionsparameter übergeben.
Ergebnis `$pageItem->getUrl(): /catalogsearch/result/?followSearch=9950&verbose=true&q=euro&p=6` Wird aber nicht in _pagingUrls hinterlegt

**Ergebnis:**
```
// pager > limiter
<select onchange="setLocation(this.value)">
    <option value="" selected="selected">12</option>
    <option value="">24</option>
    <option value="">50</option>
    <option value="">All</option>
</select>
```

Wenn ich `if (!$this->getPaging()) {` auskommentiere und `parent::getPagerUrl($params);` aufgerufen wird, ist das Ergebnis wie zu erwarten!

```
<select onchange="setLocation(this.value)">
    <option value="http://xyz/catalogsearch/result/index/?limit=12&amp;q=euro" selected="selected">12</option>
    <option value="http://xyz/catalogsearch/result/index/?limit=24&amp;q=euro">24</option>
    <option value="http://xyz/catalogsearch/result/index/?limit=50&amp;q=euro">50</option>
    <option value="http://xyz/catalogsearch/result/index/?limit=all&amp;q=euro">All</option>
</select>
```

**Comment by mentizm** [comment]
Hi, 
we wait for an answer since 30 days. Maybe it is not an important issue for you but for us. We cant control the Limitation. It would be great if some of your Supporters can give us an answer. So we can fix this bug in a clean way in our system.

**Comment by mbraeuner** [comment]
@jackjackde sorry, i didn't get an notification for your your reply. I'll have an look into it.

**Comment by mbraeuner** [comment]
@jackjackde I spent couple of hours. I can't reproduce the behavior. Give me a call please. I'm back in office at tuesday.

**Comment by mbraeuner** [comment]
This was a custom template problem
