### ISSUE TITLE
enable keyboard cursors in suggest

### ISSUE THREAD

**Issue by rudibatt** [Flagbit/Magento-FACTFinder#39]
it should be possible by default to use the up/down cursors to navigate inside suggest

**Comment by tkn98** [comment]
Just a little update after some years :)

1. The first problem with the cursor keys movement should be already solved. At least it worked for me when I tried this some days ago.
2. For the second problem with the enter key I just filed a pull-request: #96 - It's a simple fix on suggest.js

So when you merge the PR this issue most likely can be closed.

**Comment by rudibatt** [comment]
:+1:
