### ISSUE TITLE
for requesting product campaign not ID but SKU should be used

### ISSUE THREAD

**Issue by rudibatt** [Flagbit/Magento-FACTFinder#71]
FACT-Finder does not expect the database id at product-campaign requests, but the article number (which is the SKU)

**Comment by tuegeb** [comment]
Configurable since version 4 (RC already available: https://github.com/Flagbit/Magento-FACTFinder/releases/tag/v4.0.0-rc.1, latest revision in branch https://github.com/Flagbit/Magento-FACTFinder/tree/next)
