### ISSUE TITLE
too often "String could not be parsed as XML" reported when using version 3.5.5 with FF6.9

### ISSUE THREAD

**Issue by omikron-net** [Flagbit/Magento-FACTFinder#81]
Could you please check if there has been introduced a bug with the tracking bug fix in this version.

Many thanks.

**Comment by cmuench** [comment]
This could be the result of a curl timeout. In this case the XML string is empty.

**Comment by ansgarbecker** [comment]
We also experience this issue, a lot of times a day. Though it does not look like a timeout, as the error returns immediately after the request.

**Comment by xpoback** [comment]
@ansgarbecker Can you please send us the whole message you get and under which circumstances?

**Comment by ansgarbecker** [comment]
After updating to v4.x these errors seem to be fixed.
