### ISSUE TITLE
Slider should be loaded from according protocol

### ISSUE THREAD

**Issue by rudibatt** [Flagbit/Magento-FACTFinder#84]
At https://github.com/Flagbit/Magento-FACTFinder/blob/master/src/app/code/community/Flagbit/FactFinder/Block/Filter/Slider.php
the slider URL is loaded strictly from http. That should be done dynamically using the protocol the according user. This is possible by removing the "http:" part from the URI for example.

**Comment by thakilla** [comment]
The js file doesn't seem to be reachable through https ;)

**Comment by rudibatt** [comment]
Oh crap... Ok, then I suggest to replace the slider with a standard slider. Is there on at Magento?

**Comment by thakilla** [comment]
Nope, no slider included.
I also think we should ship the ff slider with the module.

**Comment by rudibatt** [comment]
Could you do that, please?

**Comment by HJK181** [comment]
Any update on this?

**Comment by tuegeb** [comment]
Solved in version 4 (RC already available: https://github.com/Flagbit/Magento-FACTFinder/releases/tag/v4.0.0-rc.1, latest revision in branch https://github.com/Flagbit/Magento-FACTFinder/tree/next)
