### ISSUE TITLE
ProxyController sets wrong response header

### ISSUE THREAD

**Issue by HJK181** [Flagbit/Magento-FACTFinder#86]
In line 47 of ProxyController.php:
`$this->getResponse()->setHeader("Content-Type:", "text/javascript;charset=utf-8", true);`
the "Content-Type:" leads to the following header response if the shop is using the proxy for suggest:

`Content-Type:: text/javascript;charset=utf-8`
The browser will than interpret that as text/plain leading to a not working callback. This may not effect every Magento version as I don't know the setHeader(..) implementation details.

**Comment by xpoback** [comment]
In the version >= 4.0 that line looks like:
    `$this->getResponse()->setHeader("Content-Type:", "application/json;charset=utf-8", true);`

**Comment by wesseloh-as** [comment]
OW, it looks like it's the other way around?

I thought I have fixed that in our environment, since Chrome has blocked JSONP responses with content-type `application/json`.

I am a little confused now.
