### ISSUE TITLE
Class not found in Flagbit_FactFinder_Model_Handler_SecondarySearch

### ISSUE THREAD

**Issue by aboritskiy** [Flagbit/Magento-FACTFinder#87]
Got an error on line 22 of `Flagbit_FactFinder_Model_Handler_SecondarySearch`:

       $this->_secondaryChannels = FF::getSingleton('configuration')->getSecondaryChannels();

Class 'FF' not found. The issue can be fixed by adding 

       require_once BP.DS.'lib'.DS.'FACTFinder'.DS.'Loader.php';

to the top of above-mentioned file. But that might indicate some other bigger issue, not sure about that.

**Comment by thakilla** [comment]
I guess that problem happens when the main channel is empty.

Could you try to add "$this->_getFacade()->configureSearchAdapter(array(), $channel);" as the first line of "function configureFacade()".
