### ISSUE TITLE
Inline styles added to the search_autocomplete element

### ISSUE THREAD

**Issue by dmanners** [Flagbit/Magento-FACTFinder#89]
When working with the auto complete functionality we have noticed that there are inline styles added to the element search_autocomplete.

Could you please let us know where these styles come from as for IE9 they are not working. Are these from FactFinder?

**Comment by aboritskiy** [comment]
We've worked that around with static CSS values with !important flag, since inline styles for IE are not correct and our layout allowed that. But would be great to go for better approach.

**Comment by drlrdsen** [comment]
This is a JavaScript Prototype default function that toggles visibility of the autocomplete layer. I know this reaction comes a bit late, but is this still a valid problem? IE9 is not much of a deal anymore. This should be working in most of the browsers around.
