### ISSUE TITLE
Search results are slow

### ISSUE THREAD

**Issue by Nasatya** [Flagbit/Magento-FACTFinder#90]
I have a problem with the speed of showing my results.
When I type into the textfield the results are not showing immediately, like they are on my fact-finder site. I also compared the speed to other websites, that are using this extension on Magento and by all I can see the normal speed of results after typing in two or three letters. 
I also reinstalled the extension to a newer version but i didn't help either. After typing three letters, there is still no immediate result in my window. What can be influencing my search results in drop down window on my website?

**Comment by thakilla** [comment]
Do you use the suggest proxy mode? In that case the request is done by magento which delays the result a bit. If proxy mode is disabled, the search request is done directly from the browser.

**Comment by Nasatya** [comment]
Well, I have 'Use Proxy for Suggest' set on No.

**Comment by rudibatt** [comment]
So there is no suggestions at all or just slow ones? The suggest script is having a small delay before even sending the request. Maybe this could be it?

**Comment by rudibatt** [comment]
Here are the details:
- the FactFinderAutocompleter is an extension of the scriptaculous Ajax.Autocompleter: https://github.com/Flagbit/Magento-FACTFinder/blob/master/src/js/factfinder/suggest.js#L115
- this Autocompleter has a "frequency" option that is not explicitly set inside the suggest.js, so the default of 0.4s would be used. I guess this option is responsible for that delay.
- to change this, you would need to change the js code (or inherit from the existing code with the modification) and put that option with a value of 0.1 or 0 into the constructor: https://github.com/Flagbit/Magento-FACTFinder/blob/master/src/js/factfinder/suggest.js#L184

**Comment by Nasatya** [comment]
rudiblatt, thank you so very much. This made the suggestion results appear very fast as by other websites. I also set minChars to 1.

**Comment by rudibatt** [comment]
nice =)
