### ISSUE TITLE
% in category name leads to wrong encoded category filter key

### ISSUE THREAD

**Issue by HJK181** [Flagbit/Magento-FACTFinder#97]
Currently the module only encodes + and / when creating the category filter key, see Search.php line 80 and 144:
```php
$filterKey .= '/'.str_replace('+', '%2B', str_replace('/', '%2F', $category));
```
This is necessary because FACT-Finder stores the category entries URL encoded.

A category named % Sale will currently lead to a filter key: 
> filtercategoryROOT%2F%25+Sale=Spar-Packs

The index entry however looks like:
> |...categoryROOT/%25 Sale=Spar-Packs...|

The correct filter would be:
> filtercategoryROOT%2F%2525+Sale=Spar-Packs

Because FACT-Finder decodes the passed filter
A possible fix for line 80, 144 could be:
```php
$filterKey = '/'.str_replace(array('%', '+', '/'), array('%25', '%2B', '%2F'), $category);
```

**Comment by sgrund** [comment]
You should also check line 145 in Seach.php:

$filterKey .= '/'.str_replace('+', '%2B', str_replace('/', '%2F', str_replace('%', '%25',$category)));

**Comment by tuegeb** [comment]
Solved in version 4 (RC already available: https://github.com/Flagbit/Magento-FACTFinder/releases/tag/v4.0.0-rc.1, latest revision in branch https://github.com/Flagbit/Magento-FACTFinder/tree/next)
