### ISSUE TITLE
Fact-Finder v7 Support

### ISSUE THREAD

**Issue by Bobspadger** [Flagbit/Magento-FACTFinder#98]
Hi Folks

do you have an ETA on FF v7 support for this module ?

Thanks

Alex

**Comment by tuegeb** [comment]
The version 4 of this module (RC already available: https://github.com/Flagbit/Magento-FACTFinder/releases/tag/v4.0.0-rc.1, latest revision in branch https://github.com/Flagbit/Magento-FACTFinder/tree/next) supports FF v6.9 - v7.0.

**Comment by Bobspadger** [comment]
ah - fantastic.

Would this be stable enough for production use or is it not ready for that yet >

**Comment by tuegeb** [comment]
From my point of view it's ready for production use (Quality assurance is already passed). Only the wiki documentation isn't 100 % updated so far.
