### ISSUE TITLE
Duplicate Export Headers in Multi-Store Environment

### ISSUE THREAD

**Issue by Shadowsvoices** [Flagbit/Magento-FACTFinder#99]
Hello,

I've recently been having issues with the **"next" Branch** in a **multi-store view environment** where the **product export** contained  **duplicate column headers for 'image' and 'deeplink'**. Debugging has revealed that this occurs because of the following lines of code:

**Class: FACTFinder_Core_Model_Export_Product**
**Line: 154~158**
``` php
            if (Mage::getStoreConfigFlag('factfinder/export/urls', $storeId)) {
                $this->_deafultHeader[] = 'image';
                $this->_deafultHeader[] = 'deeplink';
                $this->_imageHelper = Mage::helper('catalog/image');
            }
```

The columns 'image' and 'deeplink' get added to the _defaultHeaders field for each store view, resulting in 2 more duplicates for every consecutive store view that gets processed as the _defaultHeaders field is not reset.

There is also a **spelling mistake in "_deafultHeader"** class field.

I **temporarily fixed** this my moving the 'image' and 'deeplink' from _defaultHeaders to a local variable ($additonalAttributes) because those seem to be configurable for each store view separately (in Magento Admin Config) anyway and therefor shouldn't be in the _defaultHeaders anyway. 

``` php
            // new local variable
            $additionalAttributes = [];
            if (Mage::getStoreConfigFlag('factfinder/export/urls', $storeId)) {
                $additionalAttributes[] = 'image';
                $additionalAttributes[] = 'deeplink';
                $this->_imageHelper = Mage::helper('catalog/image');
            }

            // ...
            // truncated other field setup
            // ...

            $this->_exportAttributeCodes[$storeId] = array_merge(
                $this->_deafultHeader,
                $additionalAttributes, // add new local variable from above
                array_keys($headerSetup)
            );
```

**Comment by xpoback** [comment]
Thank you for contribution. 
I used your fix and now it'll be permanent
